// See LICENSE file in the project root for license information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/webtty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_Type int32

const (
	Data_TYPE_STDIN  Data_Type = 0
	Data_TYPE_STDOUT Data_Type = 1
	Data_TYPE_STDERR Data_Type = 2
)

// Enum value maps for Data_Type.
var (
	Data_Type_name = map[int32]string{
		0: "TYPE_STDIN",
		1: "TYPE_STDOUT",
		2: "TYPE_STDERR",
	}
	Data_Type_value = map[string]int32{
		"TYPE_STDIN":  0,
		"TYPE_STDOUT": 1,
		"TYPE_STDERR": 2,
	}
)

func (x Data_Type) Enum() *Data_Type {
	p := new(Data_Type)
	*p = x
	return p
}

func (x Data_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_webtty_proto_enumTypes[0].Descriptor()
}

func (Data_Type) Type() protoreflect.EnumType {
	return &file_pb_webtty_proto_enumTypes[0]
}

func (x Data_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_Type.Descriptor instead.
func (Data_Type) EnumDescriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{10, 0}
}

type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interactive   bool                   `protobuf:"varint,1,opt,name=interactive,proto3" json:"interactive,omitempty"`
	AllocateTty   bool                   `protobuf:"varint,2,opt,name=allocate_tty,json=allocateTty,proto3" json:"allocate_tty,omitempty"`
	SendHeartbeat bool                   `protobuf:"varint,3,opt,name=send_heartbeat,json=sendHeartbeat,proto3" json:"send_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_pb_webtty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *Options) GetAllocateTty() bool {
	if x != nil {
		return x.AllocateTty
	}
	return false
}

func (x *Options) GetSendHeartbeat() bool {
	if x != nil {
		return x.SendHeartbeat
	}
	return false
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_pb_webtty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{1}
}

func (x *Environment) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Environment) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Username struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Username_Name
	//	*Username_Id
	Payload       isUsername_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Username) Reset() {
	*x = Username{}
	mi := &file_pb_webtty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Username) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Username) ProtoMessage() {}

func (x *Username) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Username.ProtoReflect.Descriptor instead.
func (*Username) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{2}
}

func (x *Username) GetPayload() isUsername_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Username) GetName() string {
	if x != nil {
		if x, ok := x.Payload.(*Username_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *Username) GetId() uint32 {
	if x != nil {
		if x, ok := x.Payload.(*Username_Id); ok {
			return x.Id
		}
	}
	return 0
}

type isUsername_Payload interface {
	isUsername_Payload()
}

type Username_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type Username_Id struct {
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*Username_Name) isUsername_Payload() {}

func (*Username_Id) isUsername_Payload() {}

type Workdir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workdir) Reset() {
	*x = Workdir{}
	mi := &file_pb_webtty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workdir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workdir) ProtoMessage() {}

func (x *Workdir) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workdir.ProtoReflect.Descriptor instead.
func (*Workdir) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{3}
}

func (x *Workdir) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Options               `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	CmdArgs       []string               `protobuf:"bytes,2,rep,name=cmd_args,json=cmdArgs,proto3" json:"cmd_args,omitempty"`
	EnvVars       []*Environment         `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	Workdir       *Workdir               `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Username      *Username              `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pb_webtty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Config) GetCmdArgs() []string {
	if x != nil {
		return x.CmdArgs
	}
	return nil
}

func (x *Config) GetEnvVars() []*Environment {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *Config) GetWorkdir() *Workdir {
	if x != nil {
		return x.Workdir
	}
	return nil
}

func (x *Config) GetUsername() *Username {
	if x != nil {
		return x.Username
	}
	return nil
}

type Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Open) Reset() {
	*x = Open{}
	mi := &file_pb_webtty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{5}
}

func (x *Open) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pb_webtty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{6}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pb_webtty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    int32                  `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_pb_webtty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{8}
}

func (x *Close) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

type EndOfStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndOfStream) Reset() {
	*x = EndOfStream{}
	mi := &file_pb_webtty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndOfStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndOfStream) ProtoMessage() {}

func (x *EndOfStream) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndOfStream.ProtoReflect.Descriptor instead.
func (*EndOfStream) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{9}
}

type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Data_Type              `protobuf:"varint,1,opt,name=type,proto3,enum=Data_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Data_Data
	//	*Data_Eos
	Payload       isData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_pb_webtty_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{10}
}

func (x *Data) GetType() Data_Type {
	if x != nil {
		return x.Type
	}
	return Data_TYPE_STDIN
}

func (x *Data) GetPayload() isData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Data) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Data_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Data) GetEos() *EndOfStream {
	if x != nil {
		if x, ok := x.Payload.(*Data_Eos); ok {
			return x.Eos
		}
	}
	return nil
}

type isData_Payload interface {
	isData_Payload()
}

type Data_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type Data_Eos struct {
	Eos *EndOfStream `protobuf:"bytes,3,opt,name=eos,proto3,oneof"`
}

func (*Data_Data) isData_Payload() {}

func (*Data_Eos) isData_Payload() {}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           uint32                 `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Xpixel        uint32                 `protobuf:"varint,3,opt,name=xpixel,proto3" json:"xpixel,omitempty"`
	Ypixel        uint32                 `protobuf:"varint,4,opt,name=ypixel,proto3" json:"ypixel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_pb_webtty_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{11}
}

func (x *TerminalSize) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *TerminalSize) GetCol() uint32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *TerminalSize) GetXpixel() uint32 {
	if x != nil {
		return x.Xpixel
	}
	return 0
}

func (x *TerminalSize) GetYpixel() uint32 {
	if x != nil {
		return x.Ypixel
	}
	return 0
}

type Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Parameter:
	//
	//	*Parameter_TerminalSize
	Parameter     isParameter_Parameter `protobuf_oneof:"parameter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_pb_webtty_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{12}
}

func (x *Parameter) GetParameter() isParameter_Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *Parameter) GetTerminalSize() *TerminalSize {
	if x != nil {
		if x, ok := x.Parameter.(*Parameter_TerminalSize); ok {
			return x.TerminalSize
		}
	}
	return nil
}

type isParameter_Parameter interface {
	isParameter_Parameter()
}

type Parameter_TerminalSize struct {
	TerminalSize *TerminalSize `protobuf:"bytes,1,opt,name=terminal_size,json=terminalSize,proto3,oneof"`
}

func (*Parameter_TerminalSize) isParameter_Parameter() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pb_webtty_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{13}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Open
	//	*Message_Ack
	//	*Message_Error
	//	*Message_Close
	//	*Message_Data
	//	*Message_Parameter
	//	*Message_Heartbeat
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_webtty_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_webtty_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_webtty_proto_rawDescGZIP(), []int{14}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetOpen() *Open {
	if x != nil {
		if x, ok := x.Payload.(*Message_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *Message) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Message_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Message_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Message) GetClose() *Close {
	if x != nil {
		if x, ok := x.Payload.(*Message_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Message) GetData() *Data {
	if x != nil {
		if x, ok := x.Payload.(*Message_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Message) GetParameter() *Parameter {
	if x != nil {
		if x, ok := x.Payload.(*Message_Parameter); ok {
			return x.Parameter
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Message_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Open struct {
	Open *Open `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Message_Close struct {
	Close *Close `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type Message_Data struct {
	Data *Data `protobuf:"bytes,5,opt,name=data,proto3,oneof"`
}

type Message_Parameter struct {
	Parameter *Parameter `protobuf:"bytes,6,opt,name=parameter,proto3,oneof"`
}

type Message_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"`
}

func (*Message_Open) isMessage_Payload() {}

func (*Message_Ack) isMessage_Payload() {}

func (*Message_Error) isMessage_Payload() {}

func (*Message_Close) isMessage_Payload() {}

func (*Message_Data) isMessage_Payload() {}

func (*Message_Parameter) isMessage_Payload() {}

func (*Message_Heartbeat) isMessage_Payload() {}

var File_pb_webtty_proto protoreflect.FileDescriptor

const file_pb_webtty_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/webtty.proto\"u\n" +
	"\aOptions\x12 \n" +
	"\vinteractive\x18\x01 \x01(\bR\vinteractive\x12!\n" +
	"\fallocate_tty\x18\x02 \x01(\bR\vallocateTty\x12%\n" +
	"\x0esend_heartbeat\x18\x03 \x01(\bR\rsendHeartbeat\"5\n" +
	"\vEnvironment\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\bUsername\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12\x10\n" +
	"\x02id\x18\x02 \x01(\rH\x00R\x02idB\t\n" +
	"\apayload\"\x1f\n" +
	"\aWorkdir\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xbb\x01\n" +
	"\x06Config\x12\"\n" +
	"\aoptions\x18\x01 \x01(\v2\b.OptionsR\aoptions\x12\x19\n" +
	"\bcmd_args\x18\x02 \x03(\tR\acmdArgs\x12'\n" +
	"\benv_vars\x18\x03 \x03(\v2\f.EnvironmentR\aenvVars\x12\"\n" +
	"\aworkdir\x18\x04 \x01(\v2\b.WorkdirR\aworkdir\x12%\n" +
	"\busername\x18\x05 \x01(\v2\t.UsernameR\busername\"'\n" +
	"\x04Open\x12\x1f\n" +
	"\x06config\x18\x01 \x01(\v2\a.ConfigR\x06config\"\x05\n" +
	"\x03Ack\"\x19\n" +
	"\x05Error\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"(\n" +
	"\x05Close\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x05R\n" +
	"returnCode\"\r\n" +
	"\vEndOfStream\"\xa3\x01\n" +
	"\x04Data\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".Data.TypeR\x04type\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12 \n" +
	"\x03eos\x18\x03 \x01(\v2\f.EndOfStreamH\x00R\x03eos\"8\n" +
	"\x04Type\x12\x0e\n" +
	"\n" +
	"TYPE_STDIN\x10\x00\x12\x0f\n" +
	"\vTYPE_STDOUT\x10\x01\x12\x0f\n" +
	"\vTYPE_STDERR\x10\x02B\t\n" +
	"\apayload\"b\n" +
	"\fTerminalSize\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\rR\x03col\x12\x16\n" +
	"\x06xpixel\x18\x03 \x01(\rR\x06xpixel\x12\x16\n" +
	"\x06ypixel\x18\x04 \x01(\rR\x06ypixel\"N\n" +
	"\tParameter\x124\n" +
	"\rterminal_size\x18\x01 \x01(\v2\r.TerminalSizeH\x00R\fterminalSizeB\v\n" +
	"\tparameter\"\v\n" +
	"\tHeartbeat\"\x80\x02\n" +
	"\aMessage\x12\x1b\n" +
	"\x04open\x18\x01 \x01(\v2\x05.OpenH\x00R\x04open\x12\x18\n" +
	"\x03ack\x18\x02 \x01(\v2\x04.AckH\x00R\x03ack\x12\x1e\n" +
	"\x05error\x18\x03 \x01(\v2\x06.ErrorH\x00R\x05error\x12\x1e\n" +
	"\x05close\x18\x04 \x01(\v2\x06.CloseH\x00R\x05close\x12\x1b\n" +
	"\x04data\x18\x05 \x01(\v2\x05.DataH\x00R\x04data\x12*\n" +
	"\tparameter\x18\x06 \x01(\v2\n" +
	".ParameterH\x00R\tparameter\x12*\n" +
	"\theartbeat\x18\a \x01(\v2\n" +
	".HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayloadB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_webtty_proto_rawDescOnce sync.Once
	file_pb_webtty_proto_rawDescData []byte
)

func file_pb_webtty_proto_rawDescGZIP() []byte {
	file_pb_webtty_proto_rawDescOnce.Do(func() {
		file_pb_webtty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_webtty_proto_rawDesc), len(file_pb_webtty_proto_rawDesc)))
	})
	return file_pb_webtty_proto_rawDescData
}

var file_pb_webtty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_webtty_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_webtty_proto_goTypes = []any{
	(Data_Type)(0),       // 0: Data.Type
	(*Options)(nil),      // 1: Options
	(*Environment)(nil),  // 2: Environment
	(*Username)(nil),     // 3: Username
	(*Workdir)(nil),      // 4: Workdir
	(*Config)(nil),       // 5: Config
	(*Open)(nil),         // 6: Open
	(*Ack)(nil),          // 7: Ack
	(*Error)(nil),        // 8: Error
	(*Close)(nil),        // 9: Close
	(*EndOfStream)(nil),  // 10: EndOfStream
	(*Data)(nil),         // 11: Data
	(*TerminalSize)(nil), // 12: TerminalSize
	(*Parameter)(nil),    // 13: Parameter
	(*Heartbeat)(nil),    // 14: Heartbeat
	(*Message)(nil),      // 15: Message
}
var file_pb_webtty_proto_depIdxs = []int32{
	1,  // 0: Config.options:type_name -> Options
	2,  // 1: Config.env_vars:type_name -> Environment
	4,  // 2: Config.workdir:type_name -> Workdir
	3,  // 3: Config.username:type_name -> Username
	5,  // 4: Open.config:type_name -> Config
	0,  // 5: Data.type:type_name -> Data.Type
	10, // 6: Data.eos:type_name -> EndOfStream
	12, // 7: Parameter.terminal_size:type_name -> TerminalSize
	6,  // 8: Message.open:type_name -> Open
	7,  // 9: Message.ack:type_name -> Ack
	8,  // 10: Message.error:type_name -> Error
	9,  // 11: Message.close:type_name -> Close
	11, // 12: Message.data:type_name -> Data
	13, // 13: Message.parameter:type_name -> Parameter
	14, // 14: Message.heartbeat:type_name -> Heartbeat
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pb_webtty_proto_init() }
func file_pb_webtty_proto_init() {
	if File_pb_webtty_proto != nil {
		return
	}
	file_pb_webtty_proto_msgTypes[2].OneofWrappers = []any{
		(*Username_Name)(nil),
		(*Username_Id)(nil),
	}
	file_pb_webtty_proto_msgTypes[10].OneofWrappers = []any{
		(*Data_Data)(nil),
		(*Data_Eos)(nil),
	}
	file_pb_webtty_proto_msgTypes[12].OneofWrappers = []any{
		(*Parameter_TerminalSize)(nil),
	}
	file_pb_webtty_proto_msgTypes[14].OneofWrappers = []any{
		(*Message_Open)(nil),
		(*Message_Ack)(nil),
		(*Message_Error)(nil),
		(*Message_Close)(nil),
		(*Message_Data)(nil),
		(*Message_Parameter)(nil),
		(*Message_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_webtty_proto_rawDesc), len(file_pb_webtty_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_webtty_proto_goTypes,
		DependencyIndexes: file_pb_webtty_proto_depIdxs,
		EnumInfos:         file_pb_webtty_proto_enumTypes,
		MessageInfos:      file_pb_webtty_proto_msgTypes,
	}.Build()
	File_pb_webtty_proto = out.File
	file_pb_webtty_proto_goTypes = nil
	file_pb_webtty_proto_depIdxs = nil
}
