// See LICENSE file in the project root for license information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/rstream.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Addr:
	//
	//	*IpAddress_V4
	//	*IpAddress_V6
	Addr          isIpAddress_Addr `protobuf_oneof:"addr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpAddress) Reset() {
	*x = IpAddress{}
	mi := &file_pb_rstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddress) ProtoMessage() {}

func (x *IpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddress.ProtoReflect.Descriptor instead.
func (*IpAddress) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{0}
}

func (x *IpAddress) GetAddr() isIpAddress_Addr {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *IpAddress) GetV4() uint32 {
	if x != nil {
		if x, ok := x.Addr.(*IpAddress_V4); ok {
			return x.V4
		}
	}
	return 0
}

func (x *IpAddress) GetV6() []byte {
	if x != nil {
		if x, ok := x.Addr.(*IpAddress_V6); ok {
			return x.V6
		}
	}
	return nil
}

type isIpAddress_Addr interface {
	isIpAddress_Addr()
}

type IpAddress_V4 struct {
	V4 uint32 `protobuf:"fixed32,1,opt,name=v4,proto3,oneof"`
}

type IpAddress_V6 struct {
	V6 []byte `protobuf:"bytes,2,opt,name=v6,proto3,oneof"`
}

func (*IpAddress_V4) isIpAddress_Addr() {}

func (*IpAddress_V6) isIpAddress_Addr() {}

type Error struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pb_rstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

type ClientDetails struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Agent           *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Channel         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Version         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Os              *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch            *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Token           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	ProtocolVersion *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientDetails) Reset() {
	*x = ClientDetails{}
	mi := &file_pb_rstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetails) ProtoMessage() {}

func (x *ClientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetails.ProtoReflect.Descriptor instead.
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{2}
}

func (x *ClientDetails) GetAgent() *wrapperspb.StringValue {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *ClientDetails) GetChannel() *wrapperspb.StringValue {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ClientDetails) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ClientDetails) GetOs() *wrapperspb.StringValue {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *ClientDetails) GetArch() *wrapperspb.StringValue {
	if x != nil {
		return x.Arch
	}
	return nil
}

func (x *ClientDetails) GetToken() *wrapperspb.StringValue {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ClientDetails) GetProtocolVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

type ServerDetails struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Agent         *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Channel       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Version       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Plan          *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Provider      *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Update        *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDetails) Reset() {
	*x = ServerDetails{}
	mi := &file_pb_rstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDetails) ProtoMessage() {}

func (x *ServerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDetails.ProtoReflect.Descriptor instead.
func (*ServerDetails) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{3}
}

func (x *ServerDetails) GetAgent() *wrapperspb.StringValue {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *ServerDetails) GetChannel() *wrapperspb.StringValue {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ServerDetails) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ServerDetails) GetPlan() *wrapperspb.StringValue {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *ServerDetails) GetProvider() *wrapperspb.StringValue {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ServerDetails) GetRegion() *wrapperspb.StringValue {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ServerDetails) GetUpdate() *wrapperspb.StringValue {
	if x != nil {
		return x.Update
	}
	return nil
}

type TunnelProperties struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreationDate  *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Publish       *wrapperspb.BoolValue   `protobuf:"bytes,5,opt,name=publish,proto3" json:"publish,omitempty"`
	Protocol      *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Labels        map[string]string       `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Geoip         []string                `protobuf:"bytes,8,rep,name=geoip,proto3" json:"geoip,omitempty"`
	TrustedIps    []string                `protobuf:"bytes,9,rep,name=trusted_ips,json=trustedIps,proto3" json:"trusted_ips,omitempty"`
	Host          *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	TlsMode       *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	TlsAlpns      []string                `protobuf:"bytes,12,rep,name=tls_alpns,json=tlsAlpns,proto3" json:"tls_alpns,omitempty"`
	TlsMinVersion *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=tls_min_version,json=tlsMinVersion,proto3" json:"tls_min_version,omitempty"`
	TlsCiphers    []string                `protobuf:"bytes,14,rep,name=tls_ciphers,json=tlsCiphers,proto3" json:"tls_ciphers,omitempty"`
	Mtls          *wrapperspb.BoolValue   `protobuf:"bytes,15,opt,name=mtls,proto3" json:"mtls,omitempty"`
	MtlsCacertPem *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=mtls_cacert_pem,json=mtlsCacertPem,proto3" json:"mtls_cacert_pem,omitempty"`
	HttpVersion   *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=http_version,json=httpVersion,proto3" json:"http_version,omitempty"`
	HttpUseTls    *wrapperspb.BoolValue   `protobuf:"bytes,18,opt,name=http_use_tls,json=httpUseTls,proto3" json:"http_use_tls,omitempty"`
	TokenAuth     *wrapperspb.BoolValue   `protobuf:"bytes,19,opt,name=token_auth,json=tokenAuth,proto3" json:"token_auth,omitempty"`
	RstreamAuth   *wrapperspb.BoolValue   `protobuf:"bytes,20,opt,name=rstream_auth,json=rstreamAuth,proto3" json:"rstream_auth,omitempty"`
	ChallengeMode *wrapperspb.BoolValue   `protobuf:"bytes,21,opt,name=challenge_mode,json=challengeMode,proto3" json:"challenge_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelProperties) Reset() {
	*x = TunnelProperties{}
	mi := &file_pb_rstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelProperties) ProtoMessage() {}

func (x *TunnelProperties) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelProperties.ProtoReflect.Descriptor instead.
func (*TunnelProperties) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelProperties) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TunnelProperties) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *TunnelProperties) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *TunnelProperties) GetType() *wrapperspb.StringValue {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TunnelProperties) GetPublish() *wrapperspb.BoolValue {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *TunnelProperties) GetProtocol() *wrapperspb.StringValue {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *TunnelProperties) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TunnelProperties) GetGeoip() []string {
	if x != nil {
		return x.Geoip
	}
	return nil
}

func (x *TunnelProperties) GetTrustedIps() []string {
	if x != nil {
		return x.TrustedIps
	}
	return nil
}

func (x *TunnelProperties) GetHost() *wrapperspb.StringValue {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *TunnelProperties) GetTlsMode() *wrapperspb.StringValue {
	if x != nil {
		return x.TlsMode
	}
	return nil
}

func (x *TunnelProperties) GetTlsAlpns() []string {
	if x != nil {
		return x.TlsAlpns
	}
	return nil
}

func (x *TunnelProperties) GetTlsMinVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.TlsMinVersion
	}
	return nil
}

func (x *TunnelProperties) GetTlsCiphers() []string {
	if x != nil {
		return x.TlsCiphers
	}
	return nil
}

func (x *TunnelProperties) GetMtls() *wrapperspb.BoolValue {
	if x != nil {
		return x.Mtls
	}
	return nil
}

func (x *TunnelProperties) GetMtlsCacertPem() *wrapperspb.StringValue {
	if x != nil {
		return x.MtlsCacertPem
	}
	return nil
}

func (x *TunnelProperties) GetHttpVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.HttpVersion
	}
	return nil
}

func (x *TunnelProperties) GetHttpUseTls() *wrapperspb.BoolValue {
	if x != nil {
		return x.HttpUseTls
	}
	return nil
}

func (x *TunnelProperties) GetTokenAuth() *wrapperspb.BoolValue {
	if x != nil {
		return x.TokenAuth
	}
	return nil
}

func (x *TunnelProperties) GetRstreamAuth() *wrapperspb.BoolValue {
	if x != nil {
		return x.RstreamAuth
	}
	return nil
}

func (x *TunnelProperties) GetChallengeMode() *wrapperspb.BoolValue {
	if x != nil {
		return x.ChallengeMode
	}
	return nil
}

type OpenControlChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientDetails *ClientDetails         `protobuf:"bytes,1,opt,name=client_details,json=ClientDetails,proto3" json:"client_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlChannelReq) Reset() {
	*x = OpenControlChannelReq{}
	mi := &file_pb_rstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlChannelReq) ProtoMessage() {}

func (x *OpenControlChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlChannelReq.ProtoReflect.Descriptor instead.
func (*OpenControlChannelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{5}
}

func (x *OpenControlChannelReq) GetClientDetails() *ClientDetails {
	if x != nil {
		return x.ClientDetails
	}
	return nil
}

type OpenControlChannelRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OpenControlChannelRsp_Ok_
	//	*OpenControlChannelRsp_Error
	Payload       isOpenControlChannelRsp_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlChannelRsp) Reset() {
	*x = OpenControlChannelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlChannelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlChannelRsp) ProtoMessage() {}

func (x *OpenControlChannelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlChannelRsp.ProtoReflect.Descriptor instead.
func (*OpenControlChannelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{6}
}

func (x *OpenControlChannelRsp) GetPayload() isOpenControlChannelRsp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenControlChannelRsp) GetOk() *OpenControlChannelRsp_Ok {
	if x != nil {
		if x, ok := x.Payload.(*OpenControlChannelRsp_Ok_); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *OpenControlChannelRsp) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*OpenControlChannelRsp_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOpenControlChannelRsp_Payload interface {
	isOpenControlChannelRsp_Payload()
}

type OpenControlChannelRsp_Ok_ struct {
	Ok *OpenControlChannelRsp_Ok `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type OpenControlChannelRsp_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OpenControlChannelRsp_Ok_) isOpenControlChannelRsp_Payload() {}

func (*OpenControlChannelRsp_Error) isOpenControlChannelRsp_Payload() {}

type CloseControlChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseControlChannelReq) Reset() {
	*x = CloseControlChannelReq{}
	mi := &file_pb_rstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseControlChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseControlChannelReq) ProtoMessage() {}

func (x *CloseControlChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseControlChannelReq.ProtoReflect.Descriptor instead.
func (*CloseControlChannelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{7}
}

type CloseControlChannelRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseControlChannelRsp) Reset() {
	*x = CloseControlChannelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseControlChannelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseControlChannelRsp) ProtoMessage() {}

func (x *CloseControlChannelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseControlChannelRsp.ProtoReflect.Descriptor instead.
func (*CloseControlChannelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{8}
}

type OpenTunnelReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TunnelProperties *TunnelProperties      `protobuf:"bytes,2,opt,name=tunnel_properties,json=tunnelProperties,proto3" json:"tunnel_properties,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenTunnelReq) Reset() {
	*x = OpenTunnelReq{}
	mi := &file_pb_rstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelReq) ProtoMessage() {}

func (x *OpenTunnelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelReq.ProtoReflect.Descriptor instead.
func (*OpenTunnelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{9}
}

func (x *OpenTunnelReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenTunnelReq) GetTunnelProperties() *TunnelProperties {
	if x != nil {
		return x.TunnelProperties
	}
	return nil
}

type OpenTunnelRsp struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OpenTunnelRsp_TunnelProperties
	//	*OpenTunnelRsp_Error
	Payload       isOpenTunnelRsp_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnelRsp) Reset() {
	*x = OpenTunnelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelRsp) ProtoMessage() {}

func (x *OpenTunnelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelRsp.ProtoReflect.Descriptor instead.
func (*OpenTunnelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{10}
}

func (x *OpenTunnelRsp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenTunnelRsp) GetPayload() isOpenTunnelRsp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenTunnelRsp) GetTunnelProperties() *TunnelProperties {
	if x != nil {
		if x, ok := x.Payload.(*OpenTunnelRsp_TunnelProperties); ok {
			return x.TunnelProperties
		}
	}
	return nil
}

func (x *OpenTunnelRsp) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*OpenTunnelRsp_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOpenTunnelRsp_Payload interface {
	isOpenTunnelRsp_Payload()
}

type OpenTunnelRsp_TunnelProperties struct {
	TunnelProperties *TunnelProperties `protobuf:"bytes,2,opt,name=tunnel_properties,json=tunnelProperties,proto3,oneof"`
}

type OpenTunnelRsp_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*OpenTunnelRsp_TunnelProperties) isOpenTunnelRsp_Payload() {}

func (*OpenTunnelRsp_Error) isOpenTunnelRsp_Payload() {}

type CloseTunnelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelReq) Reset() {
	*x = CloseTunnelReq{}
	mi := &file_pb_rstream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelReq) ProtoMessage() {}

func (x *CloseTunnelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelReq.ProtoReflect.Descriptor instead.
func (*CloseTunnelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{11}
}

func (x *CloseTunnelReq) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type CloseTunnelRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelRsp) Reset() {
	*x = CloseTunnelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelRsp) ProtoMessage() {}

func (x *CloseTunnelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelRsp.ProtoReflect.Descriptor instead.
func (*CloseTunnelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{12}
}

func (x *CloseTunnelRsp) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type ProxyConnReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TunnelId      string                  `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	StreamId      string                  `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Secret        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	SourceIp      *IpAddress              `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConnReq) Reset() {
	*x = ProxyConnReq{}
	mi := &file_pb_rstream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConnReq) ProtoMessage() {}

func (x *ProxyConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConnReq.ProtoReflect.Descriptor instead.
func (*ProxyConnReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{13}
}

func (x *ProxyConnReq) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ProxyConnReq) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ProxyConnReq) GetSecret() *wrapperspb.StringValue {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *ProxyConnReq) GetSourceIp() *IpAddress {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

type ProxyConnRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConnRsp) Reset() {
	*x = ProxyConnRsp{}
	mi := &file_pb_rstream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConnRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConnRsp) ProtoMessage() {}

func (x *ProxyConnRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConnRsp.ProtoReflect.Descriptor instead.
func (*ProxyConnRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{14}
}

func (x *ProxyConnRsp) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ProxyConnRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ProxyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientDetails *ClientDetails         `protobuf:"bytes,1,opt,name=client_details,json=ClientDetails,proto3" json:"client_details,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ZeroRtt       *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=zero_rtt,json=zeroRtt,proto3" json:"zero_rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyReq) Reset() {
	*x = ProxyReq{}
	mi := &file_pb_rstream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyReq) ProtoMessage() {}

func (x *ProxyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyReq.ProtoReflect.Descriptor instead.
func (*ProxyReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{15}
}

func (x *ProxyReq) GetClientDetails() *ClientDetails {
	if x != nil {
		return x.ClientDetails
	}
	return nil
}

func (x *ProxyReq) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ProxyReq) GetZeroRtt() *wrapperspb.BoolValue {
	if x != nil {
		return x.ZeroRtt
	}
	return nil
}

type ProxyRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRsp) Reset() {
	*x = ProxyRsp{}
	mi := &file_pb_rstream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRsp) ProtoMessage() {}

func (x *ProxyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRsp.ProtoReflect.Descriptor instead.
func (*ProxyRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{16}
}

func (x *ProxyRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type StreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientDetails *ClientDetails         `protobuf:"bytes,1,opt,name=client_details,json=ClientDetails,proto3" json:"client_details,omitempty"`
	TunnelIdName  string                 `protobuf:"bytes,2,opt,name=tunnel_id_name,json=tunnelIdName,proto3" json:"tunnel_id_name,omitempty"`
	ZeroRtt       *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=zero_rtt,json=zeroRtt,proto3" json:"zero_rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReq) Reset() {
	*x = StreamReq{}
	mi := &file_pb_rstream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReq) ProtoMessage() {}

func (x *StreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReq.ProtoReflect.Descriptor instead.
func (*StreamReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{17}
}

func (x *StreamReq) GetClientDetails() *ClientDetails {
	if x != nil {
		return x.ClientDetails
	}
	return nil
}

func (x *StreamReq) GetTunnelIdName() string {
	if x != nil {
		return x.TunnelIdName
	}
	return ""
}

func (x *StreamReq) GetZeroRtt() *wrapperspb.BoolValue {
	if x != nil {
		return x.ZeroRtt
	}
	return nil
}

type StreamRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamRsp_StreamId
	//	*StreamRsp_Error
	Payload       isStreamRsp_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRsp) Reset() {
	*x = StreamRsp{}
	mi := &file_pb_rstream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRsp) ProtoMessage() {}

func (x *StreamRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRsp.ProtoReflect.Descriptor instead.
func (*StreamRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{18}
}

func (x *StreamRsp) GetPayload() isStreamRsp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamRsp) GetStreamId() string {
	if x != nil {
		if x, ok := x.Payload.(*StreamRsp_StreamId); ok {
			return x.StreamId
		}
	}
	return ""
}

func (x *StreamRsp) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*StreamRsp_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamRsp_Payload interface {
	isStreamRsp_Payload()
}

type StreamRsp_StreamId struct {
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3,oneof"`
}

type StreamRsp_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamRsp_StreamId) isStreamRsp_Payload() {}

func (*StreamRsp_Error) isStreamRsp_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pb_rstream_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{19}
}

// Allows the server to send unsolicited messages to the client
type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pb_rstream_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{20}
}

func (x *ServerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_OpenControlChannelReq
	//	*Message_OpenControlChannelRsp
	//	*Message_CloseControlChannelReq
	//	*Message_CloseControlChannelRsp
	//	*Message_OpenTunnelReq
	//	*Message_OpenTunnelRsp
	//	*Message_CloseTunnelReq
	//	*Message_CloseTunnelRsp
	//	*Message_ProxyConnReq
	//	*Message_ProxyConnRsp
	//	*Message_ProxyReq
	//	*Message_ProxyRsp
	//	*Message_StreamReq
	//	*Message_StreamRsp
	//	*Message_Heartbeat
	//	*Message_ServerMessage
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_rstream_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{21}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetOpenControlChannelReq() *OpenControlChannelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenControlChannelReq); ok {
			return x.OpenControlChannelReq
		}
	}
	return nil
}

func (x *Message) GetOpenControlChannelRsp() *OpenControlChannelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenControlChannelRsp); ok {
			return x.OpenControlChannelRsp
		}
	}
	return nil
}

func (x *Message) GetCloseControlChannelReq() *CloseControlChannelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseControlChannelReq); ok {
			return x.CloseControlChannelReq
		}
	}
	return nil
}

func (x *Message) GetCloseControlChannelRsp() *CloseControlChannelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseControlChannelRsp); ok {
			return x.CloseControlChannelRsp
		}
	}
	return nil
}

func (x *Message) GetOpenTunnelReq() *OpenTunnelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenTunnelReq); ok {
			return x.OpenTunnelReq
		}
	}
	return nil
}

func (x *Message) GetOpenTunnelRsp() *OpenTunnelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenTunnelRsp); ok {
			return x.OpenTunnelRsp
		}
	}
	return nil
}

func (x *Message) GetCloseTunnelReq() *CloseTunnelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseTunnelReq); ok {
			return x.CloseTunnelReq
		}
	}
	return nil
}

func (x *Message) GetCloseTunnelRsp() *CloseTunnelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseTunnelRsp); ok {
			return x.CloseTunnelRsp
		}
	}
	return nil
}

func (x *Message) GetProxyConnReq() *ProxyConnReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyConnReq); ok {
			return x.ProxyConnReq
		}
	}
	return nil
}

func (x *Message) GetProxyConnRsp() *ProxyConnRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyConnRsp); ok {
			return x.ProxyConnRsp
		}
	}
	return nil
}

func (x *Message) GetProxyReq() *ProxyReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyReq); ok {
			return x.ProxyReq
		}
	}
	return nil
}

func (x *Message) GetProxyRsp() *ProxyRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyRsp); ok {
			return x.ProxyRsp
		}
	}
	return nil
}

func (x *Message) GetStreamReq() *StreamReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_StreamReq); ok {
			return x.StreamReq
		}
	}
	return nil
}

func (x *Message) GetStreamRsp() *StreamRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_StreamRsp); ok {
			return x.StreamRsp
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Message_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Message) GetServerMessage() *ServerMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_ServerMessage); ok {
			return x.ServerMessage
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_OpenControlChannelReq struct {
	OpenControlChannelReq *OpenControlChannelReq `protobuf:"bytes,1,opt,name=open_control_channel_req,json=openControlChannelReq,proto3,oneof"`
}

type Message_OpenControlChannelRsp struct {
	OpenControlChannelRsp *OpenControlChannelRsp `protobuf:"bytes,2,opt,name=open_control_channel_rsp,json=openControlChannelRsp,proto3,oneof"`
}

type Message_CloseControlChannelReq struct {
	CloseControlChannelReq *CloseControlChannelReq `protobuf:"bytes,3,opt,name=close_control_channel_req,json=closeControlChannelReq,proto3,oneof"`
}

type Message_CloseControlChannelRsp struct {
	CloseControlChannelRsp *CloseControlChannelRsp `protobuf:"bytes,4,opt,name=close_control_channel_rsp,json=closeControlChannelRsp,proto3,oneof"`
}

type Message_OpenTunnelReq struct {
	OpenTunnelReq *OpenTunnelReq `protobuf:"bytes,5,opt,name=open_tunnel_req,json=openTunnelReq,proto3,oneof"`
}

type Message_OpenTunnelRsp struct {
	OpenTunnelRsp *OpenTunnelRsp `protobuf:"bytes,6,opt,name=open_tunnel_rsp,json=openTunnelRsp,proto3,oneof"`
}

type Message_CloseTunnelReq struct {
	CloseTunnelReq *CloseTunnelReq `protobuf:"bytes,7,opt,name=close_tunnel_req,json=closeTunnelReq,proto3,oneof"`
}

type Message_CloseTunnelRsp struct {
	CloseTunnelRsp *CloseTunnelRsp `protobuf:"bytes,8,opt,name=close_tunnel_rsp,json=closeTunnelRsp,proto3,oneof"`
}

type Message_ProxyConnReq struct {
	ProxyConnReq *ProxyConnReq `protobuf:"bytes,9,opt,name=proxy_conn_req,json=proxyConnReq,proto3,oneof"`
}

type Message_ProxyConnRsp struct {
	ProxyConnRsp *ProxyConnRsp `protobuf:"bytes,10,opt,name=proxy_conn_rsp,json=proxyConnRsp,proto3,oneof"`
}

type Message_ProxyReq struct {
	ProxyReq *ProxyReq `protobuf:"bytes,11,opt,name=proxy_req,json=proxyReq,proto3,oneof"`
}

type Message_ProxyRsp struct {
	ProxyRsp *ProxyRsp `protobuf:"bytes,12,opt,name=proxy_rsp,json=proxyRsp,proto3,oneof"`
}

type Message_StreamReq struct {
	StreamReq *StreamReq `protobuf:"bytes,13,opt,name=stream_req,json=streamReq,proto3,oneof"`
}

type Message_StreamRsp struct {
	StreamRsp *StreamRsp `protobuf:"bytes,14,opt,name=stream_rsp,json=streamRsp,proto3,oneof"`
}

type Message_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,15,opt,name=heartbeat,proto3,oneof"`
}

type Message_ServerMessage struct {
	ServerMessage *ServerMessage `protobuf:"bytes,16,opt,name=server_message,json=serverMessage,proto3,oneof"`
}

func (*Message_OpenControlChannelReq) isMessage_Payload() {}

func (*Message_OpenControlChannelRsp) isMessage_Payload() {}

func (*Message_CloseControlChannelReq) isMessage_Payload() {}

func (*Message_CloseControlChannelRsp) isMessage_Payload() {}

func (*Message_OpenTunnelReq) isMessage_Payload() {}

func (*Message_OpenTunnelRsp) isMessage_Payload() {}

func (*Message_CloseTunnelReq) isMessage_Payload() {}

func (*Message_CloseTunnelRsp) isMessage_Payload() {}

func (*Message_ProxyConnReq) isMessage_Payload() {}

func (*Message_ProxyConnRsp) isMessage_Payload() {}

func (*Message_ProxyReq) isMessage_Payload() {}

func (*Message_ProxyRsp) isMessage_Payload() {}

func (*Message_StreamReq) isMessage_Payload() {}

func (*Message_StreamRsp) isMessage_Payload() {}

func (*Message_Heartbeat) isMessage_Payload() {}

func (*Message_ServerMessage) isMessage_Payload() {}

type OpenControlChannelRsp_Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ServerDetails *ServerDetails         `protobuf:"bytes,2,opt,name=server_details,json=serverDetails,proto3" json:"server_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlChannelRsp_Ok) Reset() {
	*x = OpenControlChannelRsp_Ok{}
	mi := &file_pb_rstream_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlChannelRsp_Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlChannelRsp_Ok) ProtoMessage() {}

func (x *OpenControlChannelRsp_Ok) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlChannelRsp_Ok.ProtoReflect.Descriptor instead.
func (*OpenControlChannelRsp_Ok) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{6, 0}
}

func (x *OpenControlChannelRsp_Ok) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OpenControlChannelRsp_Ok) GetServerDetails() *ServerDetails {
	if x != nil {
		return x.ServerDetails
	}
	return nil
}

var file_pb_rstream_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51000,
		Name:          "rstream.io_rstrm.protobuf.protocol_version",
		Tag:           "bytes,51000,opt,name=protocol_version",
		Filename:      "pb/rstream.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51234,
		Name:          "rstream.io_rstrm.protobuf.access",
		Tag:           "bytes,51234,opt,name=access",
		Filename:      "pb/rstream.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string protocol_version = 51000;
	E_ProtocolVersion = &file_pb_rstream_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string access = 51234;
	E_Access = &file_pb_rstream_proto_extTypes[1]
)

var File_pb_rstream_proto protoreflect.FileDescriptor

const file_pb_rstream_proto_rawDesc = "" +
	"\n" +
	"\x10pb/rstream.proto\x12\x19rstream.io_rstrm.protobuf\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"7\n" +
	"\tIpAddress\x12\x10\n" +
	"\x02v4\x18\x01 \x01(\aH\x00R\x02v4\x12\x10\n" +
	"\x02v6\x18\x02 \x01(\fH\x00R\x02v6B\x06\n" +
	"\x04addr\"S\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x126\n" +
	"\amessage\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\"\x90\x03\n" +
	"\rClientDetails\x122\n" +
	"\x05agent\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05agent\x126\n" +
	"\achannel\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\achannel\x126\n" +
	"\aversion\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x12,\n" +
	"\x02os\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x02os\x120\n" +
	"\x04arch\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x04arch\x122\n" +
	"\x05token\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05token\x12G\n" +
	"\x10protocol_version\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x0fprotocolVersion\"\x8b\x03\n" +
	"\rServerDetails\x122\n" +
	"\x05agent\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05agent\x126\n" +
	"\achannel\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\achannel\x126\n" +
	"\aversion\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x120\n" +
	"\x04plan\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x04plan\x128\n" +
	"\bprovider\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\bprovider\x124\n" +
	"\x06region\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x06region\x124\n" +
	"\x06update\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x06update\"\x87\f\n" +
	"\x10TunnelProperties\x12;\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\r\x92\x82\x19\tread-onlyR\x02id\x12N\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\r\x92\x82\x19\tread-onlyR\fcreationDate\x12@\n" +
	"\x04name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x04name\x12@\n" +
	"\x04type\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x04type\x12D\n" +
	"\apublish\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\apublish\x12H\n" +
	"\bprotocol\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\bprotocol\x12_\n" +
	"\x06labels\x18\a \x03(\v27.rstream.io_rstrm.protobuf.TunnelProperties.LabelsEntryB\x0e\x92\x82\x19\n" +
	"read-writeR\x06labels\x12$\n" +
	"\x05geoip\x18\b \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\x05geoip\x12/\n" +
	"\vtrusted_ips\x18\t \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\n" +
	"trustedIps\x12@\n" +
	"\x04host\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x04host\x12G\n" +
	"\btls_mode\x18\v \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\atlsMode\x12+\n" +
	"\ttls_alpns\x18\f \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\btlsAlpns\x12T\n" +
	"\x0ftls_min_version\x18\r \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\rtlsMinVersion\x12/\n" +
	"\vtls_ciphers\x18\x0e \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\n" +
	"tlsCiphers\x12>\n" +
	"\x04mtls\x18\x0f \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x04mtls\x12T\n" +
	"\x0fmtls_cacert_pem\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\rmtlsCacertPem\x12O\n" +
	"\fhttp_version\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\vhttpVersion\x12L\n" +
	"\fhttp_use_tls\x18\x12 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\n" +
	"httpUseTls\x12I\n" +
	"\n" +
	"token_auth\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\ttokenAuth\x12M\n" +
	"\frstream_auth\x18\x14 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\vrstreamAuth\x12Q\n" +
	"\x0echallenge_mode\x18\x15 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\rchallengeMode\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x15OpenControlChannelReq\x12O\n" +
	"\x0eclient_details\x18\x01 \x01(\v2(.rstream.io_rstrm.protobuf.ClientDetailsR\rClientDetails\"\x97\x02\n" +
	"\x15OpenControlChannelRsp\x12E\n" +
	"\x02ok\x18\x01 \x01(\v23.rstream.io_rstrm.protobuf.OpenControlChannelRsp.OkH\x00R\x02ok\x128\n" +
	"\x05error\x18\x02 \x01(\v2 .rstream.io_rstrm.protobuf.ErrorH\x00R\x05error\x1ar\n" +
	"\x02Ok\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12O\n" +
	"\x0eserver_details\x18\x02 \x01(\v2(.rstream.io_rstrm.protobuf.ServerDetailsR\rserverDetailsB\t\n" +
	"\apayload\"\x18\n" +
	"\x16CloseControlChannelReq\"\x18\n" +
	"\x16CloseControlChannelRsp\"\x88\x01\n" +
	"\rOpenTunnelReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12X\n" +
	"\x11tunnel_properties\x18\x02 \x01(\v2+.rstream.io_rstrm.protobuf.TunnelPropertiesR\x10tunnelProperties\"\xcf\x01\n" +
	"\rOpenTunnelRsp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12Z\n" +
	"\x11tunnel_properties\x18\x02 \x01(\v2+.rstream.io_rstrm.protobuf.TunnelPropertiesH\x00R\x10tunnelProperties\x128\n" +
	"\x05error\x18\x03 \x01(\v2 .rstream.io_rstrm.protobuf.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"-\n" +
	"\x0eCloseTunnelReq\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"-\n" +
	"\x0eCloseTunnelRsp\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"\xc1\x01\n" +
	"\fProxyConnReq\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x124\n" +
	"\x06secret\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06secret\x12A\n" +
	"\tsource_ip\x18\x04 \x01(\v2$.rstream.io_rstrm.protobuf.IpAddressR\bsourceIp\"c\n" +
	"\fProxyConnRsp\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x126\n" +
	"\x05error\x18\x02 \x01(\v2 .rstream.io_rstrm.protobuf.ErrorR\x05error\"\xaf\x01\n" +
	"\bProxyReq\x12O\n" +
	"\x0eclient_details\x18\x01 \x01(\v2(.rstream.io_rstrm.protobuf.ClientDetailsR\rClientDetails\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x125\n" +
	"\bzero_rtt\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\azeroRtt\"B\n" +
	"\bProxyRsp\x126\n" +
	"\x05error\x18\x01 \x01(\v2 .rstream.io_rstrm.protobuf.ErrorR\x05error\"\xb9\x01\n" +
	"\tStreamReq\x12O\n" +
	"\x0eclient_details\x18\x01 \x01(\v2(.rstream.io_rstrm.protobuf.ClientDetailsR\rClientDetails\x12$\n" +
	"\x0etunnel_id_name\x18\x02 \x01(\tR\ftunnelIdName\x125\n" +
	"\bzero_rtt\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\azeroRtt\"o\n" +
	"\tStreamRsp\x12\x1d\n" +
	"\tstream_id\x18\x01 \x01(\tH\x00R\bstreamId\x128\n" +
	"\x05error\x18\x02 \x01(\v2 .rstream.io_rstrm.protobuf.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\v\n" +
	"\tHeartbeat\")\n" +
	"\rServerMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf5\n" +
	"\n" +
	"\aMessage\x12k\n" +
	"\x18open_control_channel_req\x18\x01 \x01(\v20.rstream.io_rstrm.protobuf.OpenControlChannelReqH\x00R\x15openControlChannelReq\x12k\n" +
	"\x18open_control_channel_rsp\x18\x02 \x01(\v20.rstream.io_rstrm.protobuf.OpenControlChannelRspH\x00R\x15openControlChannelRsp\x12n\n" +
	"\x19close_control_channel_req\x18\x03 \x01(\v21.rstream.io_rstrm.protobuf.CloseControlChannelReqH\x00R\x16closeControlChannelReq\x12n\n" +
	"\x19close_control_channel_rsp\x18\x04 \x01(\v21.rstream.io_rstrm.protobuf.CloseControlChannelRspH\x00R\x16closeControlChannelRsp\x12R\n" +
	"\x0fopen_tunnel_req\x18\x05 \x01(\v2(.rstream.io_rstrm.protobuf.OpenTunnelReqH\x00R\ropenTunnelReq\x12R\n" +
	"\x0fopen_tunnel_rsp\x18\x06 \x01(\v2(.rstream.io_rstrm.protobuf.OpenTunnelRspH\x00R\ropenTunnelRsp\x12U\n" +
	"\x10close_tunnel_req\x18\a \x01(\v2).rstream.io_rstrm.protobuf.CloseTunnelReqH\x00R\x0ecloseTunnelReq\x12U\n" +
	"\x10close_tunnel_rsp\x18\b \x01(\v2).rstream.io_rstrm.protobuf.CloseTunnelRspH\x00R\x0ecloseTunnelRsp\x12O\n" +
	"\x0eproxy_conn_req\x18\t \x01(\v2'.rstream.io_rstrm.protobuf.ProxyConnReqH\x00R\fproxyConnReq\x12O\n" +
	"\x0eproxy_conn_rsp\x18\n" +
	" \x01(\v2'.rstream.io_rstrm.protobuf.ProxyConnRspH\x00R\fproxyConnRsp\x12B\n" +
	"\tproxy_req\x18\v \x01(\v2#.rstream.io_rstrm.protobuf.ProxyReqH\x00R\bproxyReq\x12B\n" +
	"\tproxy_rsp\x18\f \x01(\v2#.rstream.io_rstrm.protobuf.ProxyRspH\x00R\bproxyRsp\x12E\n" +
	"\n" +
	"stream_req\x18\r \x01(\v2$.rstream.io_rstrm.protobuf.StreamReqH\x00R\tstreamReq\x12E\n" +
	"\n" +
	"stream_rsp\x18\x0e \x01(\v2$.rstream.io_rstrm.protobuf.StreamRspH\x00R\tstreamRsp\x12D\n" +
	"\theartbeat\x18\x0f \x01(\v2$.rstream.io_rstrm.protobuf.HeartbeatH\x00R\theartbeat\x12Q\n" +
	"\x0eserver_message\x18\x10 \x01(\v2(.rstream.io_rstrm.protobuf.ServerMessageH\x00R\rserverMessageB\t\n" +
	"\apayload:I\n" +
	"\x10protocol_version\x12\x1c.google.protobuf.FileOptions\x18\xb8\x8e\x03 \x01(\tR\x0fprotocolVersion:7\n" +
	"\x06access\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x90\x03 \x01(\tR\x06accessB\x0f\xc2\xf3\x18\x051.3.0Z\x04./pbb\x06proto3"

var (
	file_pb_rstream_proto_rawDescOnce sync.Once
	file_pb_rstream_proto_rawDescData []byte
)

func file_pb_rstream_proto_rawDescGZIP() []byte {
	file_pb_rstream_proto_rawDescOnce.Do(func() {
		file_pb_rstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rstream_proto_rawDesc), len(file_pb_rstream_proto_rawDesc)))
	})
	return file_pb_rstream_proto_rawDescData
}

var file_pb_rstream_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pb_rstream_proto_goTypes = []any{
	(*IpAddress)(nil),                 // 0: rstream.io_rstrm.protobuf.IpAddress
	(*Error)(nil),                     // 1: rstream.io_rstrm.protobuf.Error
	(*ClientDetails)(nil),             // 2: rstream.io_rstrm.protobuf.ClientDetails
	(*ServerDetails)(nil),             // 3: rstream.io_rstrm.protobuf.ServerDetails
	(*TunnelProperties)(nil),          // 4: rstream.io_rstrm.protobuf.TunnelProperties
	(*OpenControlChannelReq)(nil),     // 5: rstream.io_rstrm.protobuf.OpenControlChannelReq
	(*OpenControlChannelRsp)(nil),     // 6: rstream.io_rstrm.protobuf.OpenControlChannelRsp
	(*CloseControlChannelReq)(nil),    // 7: rstream.io_rstrm.protobuf.CloseControlChannelReq
	(*CloseControlChannelRsp)(nil),    // 8: rstream.io_rstrm.protobuf.CloseControlChannelRsp
	(*OpenTunnelReq)(nil),             // 9: rstream.io_rstrm.protobuf.OpenTunnelReq
	(*OpenTunnelRsp)(nil),             // 10: rstream.io_rstrm.protobuf.OpenTunnelRsp
	(*CloseTunnelReq)(nil),            // 11: rstream.io_rstrm.protobuf.CloseTunnelReq
	(*CloseTunnelRsp)(nil),            // 12: rstream.io_rstrm.protobuf.CloseTunnelRsp
	(*ProxyConnReq)(nil),              // 13: rstream.io_rstrm.protobuf.ProxyConnReq
	(*ProxyConnRsp)(nil),              // 14: rstream.io_rstrm.protobuf.ProxyConnRsp
	(*ProxyReq)(nil),                  // 15: rstream.io_rstrm.protobuf.ProxyReq
	(*ProxyRsp)(nil),                  // 16: rstream.io_rstrm.protobuf.ProxyRsp
	(*StreamReq)(nil),                 // 17: rstream.io_rstrm.protobuf.StreamReq
	(*StreamRsp)(nil),                 // 18: rstream.io_rstrm.protobuf.StreamRsp
	(*Heartbeat)(nil),                 // 19: rstream.io_rstrm.protobuf.Heartbeat
	(*ServerMessage)(nil),             // 20: rstream.io_rstrm.protobuf.ServerMessage
	(*Message)(nil),                   // 21: rstream.io_rstrm.protobuf.Message
	nil,                               // 22: rstream.io_rstrm.protobuf.TunnelProperties.LabelsEntry
	(*OpenControlChannelRsp_Ok)(nil),  // 23: rstream.io_rstrm.protobuf.OpenControlChannelRsp.Ok
	(*wrapperspb.StringValue)(nil),    // 24: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),      // 26: google.protobuf.BoolValue
	(*descriptorpb.FileOptions)(nil),  // 27: google.protobuf.FileOptions
	(*descriptorpb.FieldOptions)(nil), // 28: google.protobuf.FieldOptions
}
var file_pb_rstream_proto_depIdxs = []int32{
	24, // 0: rstream.io_rstrm.protobuf.Error.message:type_name -> google.protobuf.StringValue
	24, // 1: rstream.io_rstrm.protobuf.ClientDetails.agent:type_name -> google.protobuf.StringValue
	24, // 2: rstream.io_rstrm.protobuf.ClientDetails.channel:type_name -> google.protobuf.StringValue
	24, // 3: rstream.io_rstrm.protobuf.ClientDetails.version:type_name -> google.protobuf.StringValue
	24, // 4: rstream.io_rstrm.protobuf.ClientDetails.os:type_name -> google.protobuf.StringValue
	24, // 5: rstream.io_rstrm.protobuf.ClientDetails.arch:type_name -> google.protobuf.StringValue
	24, // 6: rstream.io_rstrm.protobuf.ClientDetails.token:type_name -> google.protobuf.StringValue
	24, // 7: rstream.io_rstrm.protobuf.ClientDetails.protocol_version:type_name -> google.protobuf.StringValue
	24, // 8: rstream.io_rstrm.protobuf.ServerDetails.agent:type_name -> google.protobuf.StringValue
	24, // 9: rstream.io_rstrm.protobuf.ServerDetails.channel:type_name -> google.protobuf.StringValue
	24, // 10: rstream.io_rstrm.protobuf.ServerDetails.version:type_name -> google.protobuf.StringValue
	24, // 11: rstream.io_rstrm.protobuf.ServerDetails.plan:type_name -> google.protobuf.StringValue
	24, // 12: rstream.io_rstrm.protobuf.ServerDetails.provider:type_name -> google.protobuf.StringValue
	24, // 13: rstream.io_rstrm.protobuf.ServerDetails.region:type_name -> google.protobuf.StringValue
	24, // 14: rstream.io_rstrm.protobuf.ServerDetails.update:type_name -> google.protobuf.StringValue
	24, // 15: rstream.io_rstrm.protobuf.TunnelProperties.id:type_name -> google.protobuf.StringValue
	25, // 16: rstream.io_rstrm.protobuf.TunnelProperties.creation_date:type_name -> google.protobuf.Timestamp
	24, // 17: rstream.io_rstrm.protobuf.TunnelProperties.name:type_name -> google.protobuf.StringValue
	24, // 18: rstream.io_rstrm.protobuf.TunnelProperties.type:type_name -> google.protobuf.StringValue
	26, // 19: rstream.io_rstrm.protobuf.TunnelProperties.publish:type_name -> google.protobuf.BoolValue
	24, // 20: rstream.io_rstrm.protobuf.TunnelProperties.protocol:type_name -> google.protobuf.StringValue
	22, // 21: rstream.io_rstrm.protobuf.TunnelProperties.labels:type_name -> rstream.io_rstrm.protobuf.TunnelProperties.LabelsEntry
	24, // 22: rstream.io_rstrm.protobuf.TunnelProperties.host:type_name -> google.protobuf.StringValue
	24, // 23: rstream.io_rstrm.protobuf.TunnelProperties.tls_mode:type_name -> google.protobuf.StringValue
	24, // 24: rstream.io_rstrm.protobuf.TunnelProperties.tls_min_version:type_name -> google.protobuf.StringValue
	26, // 25: rstream.io_rstrm.protobuf.TunnelProperties.mtls:type_name -> google.protobuf.BoolValue
	24, // 26: rstream.io_rstrm.protobuf.TunnelProperties.mtls_cacert_pem:type_name -> google.protobuf.StringValue
	24, // 27: rstream.io_rstrm.protobuf.TunnelProperties.http_version:type_name -> google.protobuf.StringValue
	26, // 28: rstream.io_rstrm.protobuf.TunnelProperties.http_use_tls:type_name -> google.protobuf.BoolValue
	26, // 29: rstream.io_rstrm.protobuf.TunnelProperties.token_auth:type_name -> google.protobuf.BoolValue
	26, // 30: rstream.io_rstrm.protobuf.TunnelProperties.rstream_auth:type_name -> google.protobuf.BoolValue
	26, // 31: rstream.io_rstrm.protobuf.TunnelProperties.challenge_mode:type_name -> google.protobuf.BoolValue
	2,  // 32: rstream.io_rstrm.protobuf.OpenControlChannelReq.client_details:type_name -> rstream.io_rstrm.protobuf.ClientDetails
	23, // 33: rstream.io_rstrm.protobuf.OpenControlChannelRsp.ok:type_name -> rstream.io_rstrm.protobuf.OpenControlChannelRsp.Ok
	1,  // 34: rstream.io_rstrm.protobuf.OpenControlChannelRsp.error:type_name -> rstream.io_rstrm.protobuf.Error
	4,  // 35: rstream.io_rstrm.protobuf.OpenTunnelReq.tunnel_properties:type_name -> rstream.io_rstrm.protobuf.TunnelProperties
	4,  // 36: rstream.io_rstrm.protobuf.OpenTunnelRsp.tunnel_properties:type_name -> rstream.io_rstrm.protobuf.TunnelProperties
	1,  // 37: rstream.io_rstrm.protobuf.OpenTunnelRsp.error:type_name -> rstream.io_rstrm.protobuf.Error
	24, // 38: rstream.io_rstrm.protobuf.ProxyConnReq.secret:type_name -> google.protobuf.StringValue
	0,  // 39: rstream.io_rstrm.protobuf.ProxyConnReq.source_ip:type_name -> rstream.io_rstrm.protobuf.IpAddress
	1,  // 40: rstream.io_rstrm.protobuf.ProxyConnRsp.error:type_name -> rstream.io_rstrm.protobuf.Error
	2,  // 41: rstream.io_rstrm.protobuf.ProxyReq.client_details:type_name -> rstream.io_rstrm.protobuf.ClientDetails
	26, // 42: rstream.io_rstrm.protobuf.ProxyReq.zero_rtt:type_name -> google.protobuf.BoolValue
	1,  // 43: rstream.io_rstrm.protobuf.ProxyRsp.error:type_name -> rstream.io_rstrm.protobuf.Error
	2,  // 44: rstream.io_rstrm.protobuf.StreamReq.client_details:type_name -> rstream.io_rstrm.protobuf.ClientDetails
	26, // 45: rstream.io_rstrm.protobuf.StreamReq.zero_rtt:type_name -> google.protobuf.BoolValue
	1,  // 46: rstream.io_rstrm.protobuf.StreamRsp.error:type_name -> rstream.io_rstrm.protobuf.Error
	5,  // 47: rstream.io_rstrm.protobuf.Message.open_control_channel_req:type_name -> rstream.io_rstrm.protobuf.OpenControlChannelReq
	6,  // 48: rstream.io_rstrm.protobuf.Message.open_control_channel_rsp:type_name -> rstream.io_rstrm.protobuf.OpenControlChannelRsp
	7,  // 49: rstream.io_rstrm.protobuf.Message.close_control_channel_req:type_name -> rstream.io_rstrm.protobuf.CloseControlChannelReq
	8,  // 50: rstream.io_rstrm.protobuf.Message.close_control_channel_rsp:type_name -> rstream.io_rstrm.protobuf.CloseControlChannelRsp
	9,  // 51: rstream.io_rstrm.protobuf.Message.open_tunnel_req:type_name -> rstream.io_rstrm.protobuf.OpenTunnelReq
	10, // 52: rstream.io_rstrm.protobuf.Message.open_tunnel_rsp:type_name -> rstream.io_rstrm.protobuf.OpenTunnelRsp
	11, // 53: rstream.io_rstrm.protobuf.Message.close_tunnel_req:type_name -> rstream.io_rstrm.protobuf.CloseTunnelReq
	12, // 54: rstream.io_rstrm.protobuf.Message.close_tunnel_rsp:type_name -> rstream.io_rstrm.protobuf.CloseTunnelRsp
	13, // 55: rstream.io_rstrm.protobuf.Message.proxy_conn_req:type_name -> rstream.io_rstrm.protobuf.ProxyConnReq
	14, // 56: rstream.io_rstrm.protobuf.Message.proxy_conn_rsp:type_name -> rstream.io_rstrm.protobuf.ProxyConnRsp
	15, // 57: rstream.io_rstrm.protobuf.Message.proxy_req:type_name -> rstream.io_rstrm.protobuf.ProxyReq
	16, // 58: rstream.io_rstrm.protobuf.Message.proxy_rsp:type_name -> rstream.io_rstrm.protobuf.ProxyRsp
	17, // 59: rstream.io_rstrm.protobuf.Message.stream_req:type_name -> rstream.io_rstrm.protobuf.StreamReq
	18, // 60: rstream.io_rstrm.protobuf.Message.stream_rsp:type_name -> rstream.io_rstrm.protobuf.StreamRsp
	19, // 61: rstream.io_rstrm.protobuf.Message.heartbeat:type_name -> rstream.io_rstrm.protobuf.Heartbeat
	20, // 62: rstream.io_rstrm.protobuf.Message.server_message:type_name -> rstream.io_rstrm.protobuf.ServerMessage
	3,  // 63: rstream.io_rstrm.protobuf.OpenControlChannelRsp.Ok.server_details:type_name -> rstream.io_rstrm.protobuf.ServerDetails
	27, // 64: rstream.io_rstrm.protobuf.protocol_version:extendee -> google.protobuf.FileOptions
	28, // 65: rstream.io_rstrm.protobuf.access:extendee -> google.protobuf.FieldOptions
	66, // [66:66] is the sub-list for method output_type
	66, // [66:66] is the sub-list for method input_type
	66, // [66:66] is the sub-list for extension type_name
	64, // [64:66] is the sub-list for extension extendee
	0,  // [0:64] is the sub-list for field type_name
}

func init() { file_pb_rstream_proto_init() }
func file_pb_rstream_proto_init() {
	if File_pb_rstream_proto != nil {
		return
	}
	file_pb_rstream_proto_msgTypes[0].OneofWrappers = []any{
		(*IpAddress_V4)(nil),
		(*IpAddress_V6)(nil),
	}
	file_pb_rstream_proto_msgTypes[6].OneofWrappers = []any{
		(*OpenControlChannelRsp_Ok_)(nil),
		(*OpenControlChannelRsp_Error)(nil),
	}
	file_pb_rstream_proto_msgTypes[10].OneofWrappers = []any{
		(*OpenTunnelRsp_TunnelProperties)(nil),
		(*OpenTunnelRsp_Error)(nil),
	}
	file_pb_rstream_proto_msgTypes[18].OneofWrappers = []any{
		(*StreamRsp_StreamId)(nil),
		(*StreamRsp_Error)(nil),
	}
	file_pb_rstream_proto_msgTypes[21].OneofWrappers = []any{
		(*Message_OpenControlChannelReq)(nil),
		(*Message_OpenControlChannelRsp)(nil),
		(*Message_CloseControlChannelReq)(nil),
		(*Message_CloseControlChannelRsp)(nil),
		(*Message_OpenTunnelReq)(nil),
		(*Message_OpenTunnelRsp)(nil),
		(*Message_CloseTunnelReq)(nil),
		(*Message_CloseTunnelRsp)(nil),
		(*Message_ProxyConnReq)(nil),
		(*Message_ProxyConnRsp)(nil),
		(*Message_ProxyReq)(nil),
		(*Message_ProxyRsp)(nil),
		(*Message_StreamReq)(nil),
		(*Message_StreamRsp)(nil),
		(*Message_Heartbeat)(nil),
		(*Message_ServerMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rstream_proto_rawDesc), len(file_pb_rstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_pb_rstream_proto_goTypes,
		DependencyIndexes: file_pb_rstream_proto_depIdxs,
		MessageInfos:      file_pb_rstream_proto_msgTypes,
		ExtensionInfos:    file_pb_rstream_proto_extTypes,
	}.Build()
	File_pb_rstream_proto = out.File
	file_pb_rstream_proto_goTypes = nil
	file_pb_rstream_proto_depIdxs = nil
}
