// See LICENSE file in the project root for license information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/rstream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Addr:
	//
	//	*IpAddress_V4
	//	*IpAddress_V6
	Addr          isIpAddress_Addr `protobuf_oneof:"addr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpAddress) Reset() {
	*x = IpAddress{}
	mi := &file_pb_rstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddress) ProtoMessage() {}

func (x *IpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddress.ProtoReflect.Descriptor instead.
func (*IpAddress) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{0}
}

func (x *IpAddress) GetAddr() isIpAddress_Addr {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *IpAddress) GetV4() uint32 {
	if x != nil {
		if x, ok := x.Addr.(*IpAddress_V4); ok {
			return x.V4
		}
	}
	return 0
}

func (x *IpAddress) GetV6() []byte {
	if x != nil {
		if x, ok := x.Addr.(*IpAddress_V6); ok {
			return x.V6
		}
	}
	return nil
}

type isIpAddress_Addr interface {
	isIpAddress_Addr()
}

type IpAddress_V4 struct {
	V4 uint32 `protobuf:"fixed32,1,opt,name=v4,proto3,oneof"`
}

type IpAddress_V6 struct {
	V6 []byte `protobuf:"bytes,2,opt,name=v6,proto3,oneof"`
}

func (*IpAddress_V4) isIpAddress_Addr() {}

func (*IpAddress_V6) isIpAddress_Addr() {}

type Error struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pb_rstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

type ClientDetails struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Agent           *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Os              *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch            *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Version         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Token           *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ProtocolVersion *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientDetails) Reset() {
	*x = ClientDetails{}
	mi := &file_pb_rstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetails) ProtoMessage() {}

func (x *ClientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetails.ProtoReflect.Descriptor instead.
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{2}
}

func (x *ClientDetails) GetAgent() *wrapperspb.StringValue {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *ClientDetails) GetOs() *wrapperspb.StringValue {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *ClientDetails) GetArch() *wrapperspb.StringValue {
	if x != nil {
		return x.Arch
	}
	return nil
}

func (x *ClientDetails) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ClientDetails) GetToken() *wrapperspb.StringValue {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ClientDetails) GetProtocolVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

type TunnelProperties struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreationDate   *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Name           *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Publish        *wrapperspb.BoolValue   `protobuf:"bytes,4,opt,name=publish,proto3" json:"publish,omitempty"`
	Protocol       *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Labels         map[string]string       `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Geoip          []string                `protobuf:"bytes,7,rep,name=geoip,proto3" json:"geoip,omitempty"`
	TrustedIps     []string                `protobuf:"bytes,8,rep,name=trusted_ips,json=trustedIps,proto3" json:"trusted_ips,omitempty"`
	Domain         *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	TlsMode        *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	TlsAlpns       []string                `protobuf:"bytes,11,rep,name=tls_alpns,json=tlsAlpns,proto3" json:"tls_alpns,omitempty"`
	TlsMinVersion  *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=tls_min_version,json=tlsMinVersion,proto3" json:"tls_min_version,omitempty"`
	TlsCiphers     []string                `protobuf:"bytes,13,rep,name=tls_ciphers,json=tlsCiphers,proto3" json:"tls_ciphers,omitempty"`
	Mtls           *wrapperspb.BoolValue   `protobuf:"bytes,14,opt,name=mtls,proto3" json:"mtls,omitempty"`
	MtlsCacertPem  *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=mtls_cacert_pem,json=mtlsCacertPem,proto3" json:"mtls_cacert_pem,omitempty"`
	HttpVersion    *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=http_version,json=httpVersion,proto3" json:"http_version,omitempty"`
	HttpUseTls     *wrapperspb.BoolValue   `protobuf:"bytes,17,opt,name=http_use_tls,json=httpUseTls,proto3" json:"http_use_tls,omitempty"`
	TokenAuth      *wrapperspb.BoolValue   `protobuf:"bytes,18,opt,name=token_auth,json=tokenAuth,proto3" json:"token_auth,omitempty"`
	Sso            *wrapperspb.BoolValue   `protobuf:"bytes,19,opt,name=sso,proto3" json:"sso,omitempty"`
	SsoProviders   []string                `protobuf:"bytes,20,rep,name=sso_providers,json=ssoProviders,proto3" json:"sso_providers,omitempty"`
	EmailWhitelist []string                `protobuf:"bytes,21,rep,name=email_whitelist,json=emailWhitelist,proto3" json:"email_whitelist,omitempty"`
	EmailBlacklist []string                `protobuf:"bytes,22,rep,name=email_blacklist,json=emailBlacklist,proto3" json:"email_blacklist,omitempty"`
	Challenge      *wrapperspb.BoolValue   `protobuf:"bytes,23,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TunnelProperties) Reset() {
	*x = TunnelProperties{}
	mi := &file_pb_rstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelProperties) ProtoMessage() {}

func (x *TunnelProperties) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelProperties.ProtoReflect.Descriptor instead.
func (*TunnelProperties) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelProperties) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TunnelProperties) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *TunnelProperties) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *TunnelProperties) GetPublish() *wrapperspb.BoolValue {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *TunnelProperties) GetProtocol() *wrapperspb.StringValue {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *TunnelProperties) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TunnelProperties) GetGeoip() []string {
	if x != nil {
		return x.Geoip
	}
	return nil
}

func (x *TunnelProperties) GetTrustedIps() []string {
	if x != nil {
		return x.TrustedIps
	}
	return nil
}

func (x *TunnelProperties) GetDomain() *wrapperspb.StringValue {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *TunnelProperties) GetTlsMode() *wrapperspb.StringValue {
	if x != nil {
		return x.TlsMode
	}
	return nil
}

func (x *TunnelProperties) GetTlsAlpns() []string {
	if x != nil {
		return x.TlsAlpns
	}
	return nil
}

func (x *TunnelProperties) GetTlsMinVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.TlsMinVersion
	}
	return nil
}

func (x *TunnelProperties) GetTlsCiphers() []string {
	if x != nil {
		return x.TlsCiphers
	}
	return nil
}

func (x *TunnelProperties) GetMtls() *wrapperspb.BoolValue {
	if x != nil {
		return x.Mtls
	}
	return nil
}

func (x *TunnelProperties) GetMtlsCacertPem() *wrapperspb.StringValue {
	if x != nil {
		return x.MtlsCacertPem
	}
	return nil
}

func (x *TunnelProperties) GetHttpVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.HttpVersion
	}
	return nil
}

func (x *TunnelProperties) GetHttpUseTls() *wrapperspb.BoolValue {
	if x != nil {
		return x.HttpUseTls
	}
	return nil
}

func (x *TunnelProperties) GetTokenAuth() *wrapperspb.BoolValue {
	if x != nil {
		return x.TokenAuth
	}
	return nil
}

func (x *TunnelProperties) GetSso() *wrapperspb.BoolValue {
	if x != nil {
		return x.Sso
	}
	return nil
}

func (x *TunnelProperties) GetSsoProviders() []string {
	if x != nil {
		return x.SsoProviders
	}
	return nil
}

func (x *TunnelProperties) GetEmailWhitelist() []string {
	if x != nil {
		return x.EmailWhitelist
	}
	return nil
}

func (x *TunnelProperties) GetEmailBlacklist() []string {
	if x != nil {
		return x.EmailBlacklist
	}
	return nil
}

func (x *TunnelProperties) GetChallenge() *wrapperspb.BoolValue {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type OpenControlChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientDetails *ClientDetails         `protobuf:"bytes,1,opt,name=client_details,json=clientDetails,proto3" json:"client_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlChannelReq) Reset() {
	*x = OpenControlChannelReq{}
	mi := &file_pb_rstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlChannelReq) ProtoMessage() {}

func (x *OpenControlChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlChannelReq.ProtoReflect.Descriptor instead.
func (*OpenControlChannelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{4}
}

func (x *OpenControlChannelReq) GetClientDetails() *ClientDetails {
	if x != nil {
		return x.ClientDetails
	}
	return nil
}

type OpenControlChannelRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OpenControlChannelRsp_ClientId
	//	*OpenControlChannelRsp_Error
	Payload       isOpenControlChannelRsp_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenControlChannelRsp) Reset() {
	*x = OpenControlChannelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenControlChannelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenControlChannelRsp) ProtoMessage() {}

func (x *OpenControlChannelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenControlChannelRsp.ProtoReflect.Descriptor instead.
func (*OpenControlChannelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{5}
}

func (x *OpenControlChannelRsp) GetPayload() isOpenControlChannelRsp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenControlChannelRsp) GetClientId() string {
	if x != nil {
		if x, ok := x.Payload.(*OpenControlChannelRsp_ClientId); ok {
			return x.ClientId
		}
	}
	return ""
}

func (x *OpenControlChannelRsp) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*OpenControlChannelRsp_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOpenControlChannelRsp_Payload interface {
	isOpenControlChannelRsp_Payload()
}

type OpenControlChannelRsp_ClientId struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof"`
}

type OpenControlChannelRsp_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OpenControlChannelRsp_ClientId) isOpenControlChannelRsp_Payload() {}

func (*OpenControlChannelRsp_Error) isOpenControlChannelRsp_Payload() {}

type CloseControlChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseControlChannelReq) Reset() {
	*x = CloseControlChannelReq{}
	mi := &file_pb_rstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseControlChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseControlChannelReq) ProtoMessage() {}

func (x *CloseControlChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseControlChannelReq.ProtoReflect.Descriptor instead.
func (*CloseControlChannelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{6}
}

type CloseControlChannelRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseControlChannelRsp) Reset() {
	*x = CloseControlChannelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseControlChannelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseControlChannelRsp) ProtoMessage() {}

func (x *CloseControlChannelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseControlChannelRsp.ProtoReflect.Descriptor instead.
func (*CloseControlChannelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{7}
}

type OpenTunnelReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TunnelProperties *TunnelProperties      `protobuf:"bytes,2,opt,name=tunnel_properties,json=tunnelProperties,proto3" json:"tunnel_properties,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenTunnelReq) Reset() {
	*x = OpenTunnelReq{}
	mi := &file_pb_rstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelReq) ProtoMessage() {}

func (x *OpenTunnelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelReq.ProtoReflect.Descriptor instead.
func (*OpenTunnelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{8}
}

func (x *OpenTunnelReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenTunnelReq) GetTunnelProperties() *TunnelProperties {
	if x != nil {
		return x.TunnelProperties
	}
	return nil
}

type OpenTunnelRsp struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OpenTunnelRsp_TunnelProperties
	//	*OpenTunnelRsp_Error
	Payload       isOpenTunnelRsp_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnelRsp) Reset() {
	*x = OpenTunnelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelRsp) ProtoMessage() {}

func (x *OpenTunnelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelRsp.ProtoReflect.Descriptor instead.
func (*OpenTunnelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{9}
}

func (x *OpenTunnelRsp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenTunnelRsp) GetPayload() isOpenTunnelRsp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenTunnelRsp) GetTunnelProperties() *TunnelProperties {
	if x != nil {
		if x, ok := x.Payload.(*OpenTunnelRsp_TunnelProperties); ok {
			return x.TunnelProperties
		}
	}
	return nil
}

func (x *OpenTunnelRsp) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*OpenTunnelRsp_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isOpenTunnelRsp_Payload interface {
	isOpenTunnelRsp_Payload()
}

type OpenTunnelRsp_TunnelProperties struct {
	TunnelProperties *TunnelProperties `protobuf:"bytes,2,opt,name=tunnel_properties,json=tunnelProperties,proto3,oneof"`
}

type OpenTunnelRsp_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*OpenTunnelRsp_TunnelProperties) isOpenTunnelRsp_Payload() {}

func (*OpenTunnelRsp_Error) isOpenTunnelRsp_Payload() {}

type CloseTunnelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelReq) Reset() {
	*x = CloseTunnelReq{}
	mi := &file_pb_rstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelReq) ProtoMessage() {}

func (x *CloseTunnelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelReq.ProtoReflect.Descriptor instead.
func (*CloseTunnelReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{10}
}

func (x *CloseTunnelReq) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type CloseTunnelRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelRsp) Reset() {
	*x = CloseTunnelRsp{}
	mi := &file_pb_rstream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelRsp) ProtoMessage() {}

func (x *CloseTunnelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelRsp.ProtoReflect.Descriptor instead.
func (*CloseTunnelRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{11}
}

func (x *CloseTunnelRsp) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type ProxyConnReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TunnelId      string                  `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	StreamId      string                  `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Secret        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	SourceIp      *IpAddress              `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConnReq) Reset() {
	*x = ProxyConnReq{}
	mi := &file_pb_rstream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConnReq) ProtoMessage() {}

func (x *ProxyConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConnReq.ProtoReflect.Descriptor instead.
func (*ProxyConnReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{12}
}

func (x *ProxyConnReq) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ProxyConnReq) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ProxyConnReq) GetSecret() *wrapperspb.StringValue {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *ProxyConnReq) GetSourceIp() *IpAddress {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

type ProxyConnRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConnRsp) Reset() {
	*x = ProxyConnRsp{}
	mi := &file_pb_rstream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConnRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConnRsp) ProtoMessage() {}

func (x *ProxyConnRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConnRsp.ProtoReflect.Descriptor instead.
func (*ProxyConnRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{13}
}

func (x *ProxyConnRsp) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ProxyConnRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ProxyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientDetails *ClientDetails         `protobuf:"bytes,1,opt,name=client_details,json=clientDetails,proto3" json:"client_details,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ZeroRtt       *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=zero_rtt,json=zeroRtt,proto3" json:"zero_rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyReq) Reset() {
	*x = ProxyReq{}
	mi := &file_pb_rstream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyReq) ProtoMessage() {}

func (x *ProxyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyReq.ProtoReflect.Descriptor instead.
func (*ProxyReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{14}
}

func (x *ProxyReq) GetClientDetails() *ClientDetails {
	if x != nil {
		return x.ClientDetails
	}
	return nil
}

func (x *ProxyReq) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ProxyReq) GetZeroRtt() *wrapperspb.BoolValue {
	if x != nil {
		return x.ZeroRtt
	}
	return nil
}

type ProxyRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRsp) Reset() {
	*x = ProxyRsp{}
	mi := &file_pb_rstream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRsp) ProtoMessage() {}

func (x *ProxyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRsp.ProtoReflect.Descriptor instead.
func (*ProxyRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{15}
}

func (x *ProxyRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type StreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientDetails *ClientDetails         `protobuf:"bytes,1,opt,name=client_details,json=clientDetails,proto3" json:"client_details,omitempty"`
	TunnelIdName  string                 `protobuf:"bytes,2,opt,name=tunnel_id_name,json=tunnelIdName,proto3" json:"tunnel_id_name,omitempty"`
	ZeroRtt       *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=zero_rtt,json=zeroRtt,proto3" json:"zero_rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReq) Reset() {
	*x = StreamReq{}
	mi := &file_pb_rstream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReq) ProtoMessage() {}

func (x *StreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReq.ProtoReflect.Descriptor instead.
func (*StreamReq) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{16}
}

func (x *StreamReq) GetClientDetails() *ClientDetails {
	if x != nil {
		return x.ClientDetails
	}
	return nil
}

func (x *StreamReq) GetTunnelIdName() string {
	if x != nil {
		return x.TunnelIdName
	}
	return ""
}

func (x *StreamReq) GetZeroRtt() *wrapperspb.BoolValue {
	if x != nil {
		return x.ZeroRtt
	}
	return nil
}

type StreamRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamRsp_StreamId
	//	*StreamRsp_Error
	Payload       isStreamRsp_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRsp) Reset() {
	*x = StreamRsp{}
	mi := &file_pb_rstream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRsp) ProtoMessage() {}

func (x *StreamRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRsp.ProtoReflect.Descriptor instead.
func (*StreamRsp) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{17}
}

func (x *StreamRsp) GetPayload() isStreamRsp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamRsp) GetStreamId() string {
	if x != nil {
		if x, ok := x.Payload.(*StreamRsp_StreamId); ok {
			return x.StreamId
		}
	}
	return ""
}

func (x *StreamRsp) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*StreamRsp_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamRsp_Payload interface {
	isStreamRsp_Payload()
}

type StreamRsp_StreamId struct {
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3,oneof"`
}

type StreamRsp_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamRsp_StreamId) isStreamRsp_Payload() {}

func (*StreamRsp_Error) isStreamRsp_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pb_rstream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{18}
}

// Allows the server to send unsolicited messages to the client
type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pb_rstream_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{19}
}

func (x *ServerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_OpenControlChannelReq
	//	*Message_OpenControlChannelRsp
	//	*Message_CloseControlChannelReq
	//	*Message_CloseControlChannelRsp
	//	*Message_OpenTunnelReq
	//	*Message_OpenTunnelRsp
	//	*Message_CloseTunnelReq
	//	*Message_CloseTunnelRsp
	//	*Message_ProxyConnReq
	//	*Message_ProxyConnRsp
	//	*Message_ProxyReq
	//	*Message_ProxyRsp
	//	*Message_StreamReq
	//	*Message_StreamRsp
	//	*Message_Heartbeat
	//	*Message_ServerMessage
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_rstream_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rstream_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_rstream_proto_rawDescGZIP(), []int{20}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetOpenControlChannelReq() *OpenControlChannelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenControlChannelReq); ok {
			return x.OpenControlChannelReq
		}
	}
	return nil
}

func (x *Message) GetOpenControlChannelRsp() *OpenControlChannelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenControlChannelRsp); ok {
			return x.OpenControlChannelRsp
		}
	}
	return nil
}

func (x *Message) GetCloseControlChannelReq() *CloseControlChannelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseControlChannelReq); ok {
			return x.CloseControlChannelReq
		}
	}
	return nil
}

func (x *Message) GetCloseControlChannelRsp() *CloseControlChannelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseControlChannelRsp); ok {
			return x.CloseControlChannelRsp
		}
	}
	return nil
}

func (x *Message) GetOpenTunnelReq() *OpenTunnelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenTunnelReq); ok {
			return x.OpenTunnelReq
		}
	}
	return nil
}

func (x *Message) GetOpenTunnelRsp() *OpenTunnelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_OpenTunnelRsp); ok {
			return x.OpenTunnelRsp
		}
	}
	return nil
}

func (x *Message) GetCloseTunnelReq() *CloseTunnelReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseTunnelReq); ok {
			return x.CloseTunnelReq
		}
	}
	return nil
}

func (x *Message) GetCloseTunnelRsp() *CloseTunnelRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_CloseTunnelRsp); ok {
			return x.CloseTunnelRsp
		}
	}
	return nil
}

func (x *Message) GetProxyConnReq() *ProxyConnReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyConnReq); ok {
			return x.ProxyConnReq
		}
	}
	return nil
}

func (x *Message) GetProxyConnRsp() *ProxyConnRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyConnRsp); ok {
			return x.ProxyConnRsp
		}
	}
	return nil
}

func (x *Message) GetProxyReq() *ProxyReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyReq); ok {
			return x.ProxyReq
		}
	}
	return nil
}

func (x *Message) GetProxyRsp() *ProxyRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProxyRsp); ok {
			return x.ProxyRsp
		}
	}
	return nil
}

func (x *Message) GetStreamReq() *StreamReq {
	if x != nil {
		if x, ok := x.Payload.(*Message_StreamReq); ok {
			return x.StreamReq
		}
	}
	return nil
}

func (x *Message) GetStreamRsp() *StreamRsp {
	if x != nil {
		if x, ok := x.Payload.(*Message_StreamRsp); ok {
			return x.StreamRsp
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Message_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Message) GetServerMessage() *ServerMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_ServerMessage); ok {
			return x.ServerMessage
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_OpenControlChannelReq struct {
	OpenControlChannelReq *OpenControlChannelReq `protobuf:"bytes,1,opt,name=open_control_channel_req,json=openControlChannelReq,proto3,oneof"`
}

type Message_OpenControlChannelRsp struct {
	OpenControlChannelRsp *OpenControlChannelRsp `protobuf:"bytes,2,opt,name=open_control_channel_rsp,json=openControlChannelRsp,proto3,oneof"`
}

type Message_CloseControlChannelReq struct {
	CloseControlChannelReq *CloseControlChannelReq `protobuf:"bytes,3,opt,name=close_control_channel_req,json=closeControlChannelReq,proto3,oneof"`
}

type Message_CloseControlChannelRsp struct {
	CloseControlChannelRsp *CloseControlChannelRsp `protobuf:"bytes,4,opt,name=close_control_channel_rsp,json=closeControlChannelRsp,proto3,oneof"`
}

type Message_OpenTunnelReq struct {
	OpenTunnelReq *OpenTunnelReq `protobuf:"bytes,5,opt,name=open_tunnel_req,json=openTunnelReq,proto3,oneof"`
}

type Message_OpenTunnelRsp struct {
	OpenTunnelRsp *OpenTunnelRsp `protobuf:"bytes,6,opt,name=open_tunnel_rsp,json=openTunnelRsp,proto3,oneof"`
}

type Message_CloseTunnelReq struct {
	CloseTunnelReq *CloseTunnelReq `protobuf:"bytes,7,opt,name=close_tunnel_req,json=closeTunnelReq,proto3,oneof"`
}

type Message_CloseTunnelRsp struct {
	CloseTunnelRsp *CloseTunnelRsp `protobuf:"bytes,8,opt,name=close_tunnel_rsp,json=closeTunnelRsp,proto3,oneof"`
}

type Message_ProxyConnReq struct {
	ProxyConnReq *ProxyConnReq `protobuf:"bytes,9,opt,name=proxy_conn_req,json=proxyConnReq,proto3,oneof"`
}

type Message_ProxyConnRsp struct {
	ProxyConnRsp *ProxyConnRsp `protobuf:"bytes,10,opt,name=proxy_conn_rsp,json=proxyConnRsp,proto3,oneof"`
}

type Message_ProxyReq struct {
	ProxyReq *ProxyReq `protobuf:"bytes,11,opt,name=proxy_req,json=proxyReq,proto3,oneof"`
}

type Message_ProxyRsp struct {
	ProxyRsp *ProxyRsp `protobuf:"bytes,12,opt,name=proxy_rsp,json=proxyRsp,proto3,oneof"`
}

type Message_StreamReq struct {
	StreamReq *StreamReq `protobuf:"bytes,13,opt,name=stream_req,json=streamReq,proto3,oneof"`
}

type Message_StreamRsp struct {
	StreamRsp *StreamRsp `protobuf:"bytes,14,opt,name=stream_rsp,json=streamRsp,proto3,oneof"`
}

type Message_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,15,opt,name=heartbeat,proto3,oneof"`
}

type Message_ServerMessage struct {
	ServerMessage *ServerMessage `protobuf:"bytes,16,opt,name=server_message,json=serverMessage,proto3,oneof"`
}

func (*Message_OpenControlChannelReq) isMessage_Payload() {}

func (*Message_OpenControlChannelRsp) isMessage_Payload() {}

func (*Message_CloseControlChannelReq) isMessage_Payload() {}

func (*Message_CloseControlChannelRsp) isMessage_Payload() {}

func (*Message_OpenTunnelReq) isMessage_Payload() {}

func (*Message_OpenTunnelRsp) isMessage_Payload() {}

func (*Message_CloseTunnelReq) isMessage_Payload() {}

func (*Message_CloseTunnelRsp) isMessage_Payload() {}

func (*Message_ProxyConnReq) isMessage_Payload() {}

func (*Message_ProxyConnRsp) isMessage_Payload() {}

func (*Message_ProxyReq) isMessage_Payload() {}

func (*Message_ProxyRsp) isMessage_Payload() {}

func (*Message_StreamReq) isMessage_Payload() {}

func (*Message_StreamRsp) isMessage_Payload() {}

func (*Message_Heartbeat) isMessage_Payload() {}

func (*Message_ServerMessage) isMessage_Payload() {}

var file_pb_rstream_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51000,
		Name:          "rstream.io_rstream.protobuf.protocol_version",
		Tag:           "bytes,51000,opt,name=protocol_version",
		Filename:      "pb/rstream.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51234,
		Name:          "rstream.io_rstream.protobuf.access",
		Tag:           "bytes,51234,opt,name=access",
		Filename:      "pb/rstream.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string protocol_version = 51000;
	E_ProtocolVersion = &file_pb_rstream_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string access = 51234;
	E_Access = &file_pb_rstream_proto_extTypes[1]
)

var File_pb_rstream_proto protoreflect.FileDescriptor

const file_pb_rstream_proto_rawDesc = "" +
	"\n" +
	"\x10pb/rstream.proto\x12\x1brstream.io_rstream.protobuf\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"7\n" +
	"\tIpAddress\x12\x10\n" +
	"\x02v4\x18\x01 \x01(\aH\x00R\x02v4\x12\x10\n" +
	"\x02v6\x18\x02 \x01(\fH\x00R\x02v6B\x06\n" +
	"\x04addr\"S\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x126\n" +
	"\amessage\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\"\xd8\x02\n" +
	"\rclientDetails\x122\n" +
	"\x05agent\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05agent\x12,\n" +
	"\x02os\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x02os\x120\n" +
	"\x04arch\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04arch\x126\n" +
	"\aversion\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x122\n" +
	"\x05token\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05token\x12G\n" +
	"\x10protocol_version\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x0fprotocolVersion\"\xd8\f\n" +
	"\x10TunnelProperties\x12;\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\r\x92\x82\x19\tread-onlyR\x02id\x12N\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\r\x92\x82\x19\tread-onlyR\fcreationDate\x12@\n" +
	"\x04name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x04name\x12D\n" +
	"\apublish\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\apublish\x12H\n" +
	"\bprotocol\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\bprotocol\x12a\n" +
	"\x06labels\x18\x06 \x03(\v29.rstream.io_rstream.protobuf.TunnelProperties.LabelsEntryB\x0e\x92\x82\x19\n" +
	"read-writeR\x06labels\x12$\n" +
	"\x05geoip\x18\a \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\x05geoip\x12/\n" +
	"\vtrusted_ips\x18\b \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\n" +
	"trustedIps\x12D\n" +
	"\x06domain\x18\t \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x06domain\x12G\n" +
	"\btls_mode\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\atlsMode\x12+\n" +
	"\ttls_alpns\x18\v \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\btlsAlpns\x12T\n" +
	"\x0ftls_min_version\x18\f \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\rtlsMinVersion\x12/\n" +
	"\vtls_ciphers\x18\r \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\n" +
	"tlsCiphers\x12>\n" +
	"\x04mtls\x18\x0e \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x04mtls\x12T\n" +
	"\x0fmtls_cacert_pem\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\rmtlsCacertPem\x12O\n" +
	"\fhttp_version\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueB\x0e\x92\x82\x19\n" +
	"read-writeR\vhttpVersion\x12L\n" +
	"\fhttp_use_tls\x18\x11 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\n" +
	"httpUseTls\x12I\n" +
	"\n" +
	"token_auth\x18\x12 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\ttokenAuth\x12<\n" +
	"\x03sso\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\x03sso\x123\n" +
	"\rsso_providers\x18\x14 \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\fssoProviders\x127\n" +
	"\x0femail_whitelist\x18\x15 \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\x0eemailWhitelist\x127\n" +
	"\x0femail_blacklist\x18\x16 \x03(\tB\x0e\x92\x82\x19\n" +
	"read-writeR\x0eemailBlacklist\x12H\n" +
	"\tchallenge\x18\x17 \x01(\v2\x1a.google.protobuf.BoolValueB\x0e\x92\x82\x19\n" +
	"read-writeR\tchallenge\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x15OpenControlChannelReq\x12Q\n" +
	"\x0eclient_details\x18\x01 \x01(\v2*.rstream.io_rstream.protobuf.clientDetailsR\rclientDetails\"}\n" +
	"\x15OpenControlChannelRsp\x12\x1d\n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x12:\n" +
	"\x05error\x18\x02 \x01(\v2\".rstream.io_rstream.protobuf.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x18\n" +
	"\x16CloseControlChannelReq\"\x18\n" +
	"\x16CloseControlChannelRsp\"\x8a\x01\n" +
	"\rOpenTunnelReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12Z\n" +
	"\x11tunnel_properties\x18\x02 \x01(\v2-.rstream.io_rstream.protobuf.TunnelPropertiesR\x10tunnelProperties\"\xd3\x01\n" +
	"\rOpenTunnelRsp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\\\n" +
	"\x11tunnel_properties\x18\x02 \x01(\v2-.rstream.io_rstream.protobuf.TunnelPropertiesH\x00R\x10tunnelProperties\x12:\n" +
	"\x05error\x18\x03 \x01(\v2\".rstream.io_rstream.protobuf.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"-\n" +
	"\x0eCloseTunnelReq\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"-\n" +
	"\x0eCloseTunnelRsp\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"\xc3\x01\n" +
	"\fProxyConnReq\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x124\n" +
	"\x06secret\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06secret\x12C\n" +
	"\tsource_ip\x18\x04 \x01(\v2&.rstream.io_rstream.protobuf.IpAddressR\bsourceIp\"e\n" +
	"\fProxyConnRsp\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x128\n" +
	"\x05error\x18\x02 \x01(\v2\".rstream.io_rstream.protobuf.ErrorR\x05error\"\xb1\x01\n" +
	"\bProxyReq\x12Q\n" +
	"\x0eclient_details\x18\x01 \x01(\v2*.rstream.io_rstream.protobuf.clientDetailsR\rclientDetails\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x125\n" +
	"\bzero_rtt\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\azeroRtt\"D\n" +
	"\bProxyRsp\x128\n" +
	"\x05error\x18\x01 \x01(\v2\".rstream.io_rstream.protobuf.ErrorR\x05error\"\xbb\x01\n" +
	"\tStreamReq\x12Q\n" +
	"\x0eclient_details\x18\x01 \x01(\v2*.rstream.io_rstream.protobuf.clientDetailsR\rclientDetails\x12$\n" +
	"\x0etunnel_id_name\x18\x02 \x01(\tR\ftunnelIdName\x125\n" +
	"\bzero_rtt\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\azeroRtt\"q\n" +
	"\tStreamRsp\x12\x1d\n" +
	"\tstream_id\x18\x01 \x01(\tH\x00R\bstreamId\x12:\n" +
	"\x05error\x18\x02 \x01(\v2\".rstream.io_rstream.protobuf.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\v\n" +
	"\tHeartbeat\")\n" +
	"\rServerMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x95\v\n" +
	"\aMessage\x12m\n" +
	"\x18open_control_channel_req\x18\x01 \x01(\v22.rstream.io_rstream.protobuf.OpenControlChannelReqH\x00R\x15openControlChannelReq\x12m\n" +
	"\x18open_control_channel_rsp\x18\x02 \x01(\v22.rstream.io_rstream.protobuf.OpenControlChannelRspH\x00R\x15openControlChannelRsp\x12p\n" +
	"\x19close_control_channel_req\x18\x03 \x01(\v23.rstream.io_rstream.protobuf.CloseControlChannelReqH\x00R\x16closeControlChannelReq\x12p\n" +
	"\x19close_control_channel_rsp\x18\x04 \x01(\v23.rstream.io_rstream.protobuf.CloseControlChannelRspH\x00R\x16closeControlChannelRsp\x12T\n" +
	"\x0fopen_tunnel_req\x18\x05 \x01(\v2*.rstream.io_rstream.protobuf.OpenTunnelReqH\x00R\ropenTunnelReq\x12T\n" +
	"\x0fopen_tunnel_rsp\x18\x06 \x01(\v2*.rstream.io_rstream.protobuf.OpenTunnelRspH\x00R\ropenTunnelRsp\x12W\n" +
	"\x10close_tunnel_req\x18\a \x01(\v2+.rstream.io_rstream.protobuf.CloseTunnelReqH\x00R\x0ecloseTunnelReq\x12W\n" +
	"\x10close_tunnel_rsp\x18\b \x01(\v2+.rstream.io_rstream.protobuf.CloseTunnelRspH\x00R\x0ecloseTunnelRsp\x12Q\n" +
	"\x0eproxy_conn_req\x18\t \x01(\v2).rstream.io_rstream.protobuf.ProxyConnReqH\x00R\fproxyConnReq\x12Q\n" +
	"\x0eproxy_conn_rsp\x18\n" +
	" \x01(\v2).rstream.io_rstream.protobuf.ProxyConnRspH\x00R\fproxyConnRsp\x12D\n" +
	"\tproxy_req\x18\v \x01(\v2%.rstream.io_rstream.protobuf.ProxyReqH\x00R\bproxyReq\x12D\n" +
	"\tproxy_rsp\x18\f \x01(\v2%.rstream.io_rstream.protobuf.ProxyRspH\x00R\bproxyRsp\x12G\n" +
	"\n" +
	"stream_req\x18\r \x01(\v2&.rstream.io_rstream.protobuf.StreamReqH\x00R\tstreamReq\x12G\n" +
	"\n" +
	"stream_rsp\x18\x0e \x01(\v2&.rstream.io_rstream.protobuf.StreamRspH\x00R\tstreamRsp\x12F\n" +
	"\theartbeat\x18\x0f \x01(\v2&.rstream.io_rstream.protobuf.HeartbeatH\x00R\theartbeat\x12S\n" +
	"\x0eserver_message\x18\x10 \x01(\v2*.rstream.io_rstream.protobuf.ServerMessageH\x00R\rserverMessageB\t\n" +
	"\apayload:I\n" +
	"\x10protocol_version\x12\x1c.google.protobuf.FileOptions\x18\xb8\x8e\x03 \x01(\tR\x0fprotocolVersion:7\n" +
	"\x06access\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x90\x03 \x01(\tR\x06accessB\r\xc2\xf3\x18\x031.0Z\x04./pbb\x06proto3"

var (
	file_pb_rstream_proto_rawDescOnce sync.Once
	file_pb_rstream_proto_rawDescData []byte
)

func file_pb_rstream_proto_rawDescGZIP() []byte {
	file_pb_rstream_proto_rawDescOnce.Do(func() {
		file_pb_rstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rstream_proto_rawDesc), len(file_pb_rstream_proto_rawDesc)))
	})
	return file_pb_rstream_proto_rawDescData
}

var file_pb_rstream_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pb_rstream_proto_goTypes = []any{
	(*IpAddress)(nil),                 // 0: rstream.io_rstream.protobuf.IpAddress
	(*Error)(nil),                     // 1: rstream.io_rstream.protobuf.Error
	(*ClientDetails)(nil),             // 2: rstream.io_rstream.protobuf.clientDetails
	(*TunnelProperties)(nil),          // 3: rstream.io_rstream.protobuf.TunnelProperties
	(*OpenControlChannelReq)(nil),     // 4: rstream.io_rstream.protobuf.OpenControlChannelReq
	(*OpenControlChannelRsp)(nil),     // 5: rstream.io_rstream.protobuf.OpenControlChannelRsp
	(*CloseControlChannelReq)(nil),    // 6: rstream.io_rstream.protobuf.CloseControlChannelReq
	(*CloseControlChannelRsp)(nil),    // 7: rstream.io_rstream.protobuf.CloseControlChannelRsp
	(*OpenTunnelReq)(nil),             // 8: rstream.io_rstream.protobuf.OpenTunnelReq
	(*OpenTunnelRsp)(nil),             // 9: rstream.io_rstream.protobuf.OpenTunnelRsp
	(*CloseTunnelReq)(nil),            // 10: rstream.io_rstream.protobuf.CloseTunnelReq
	(*CloseTunnelRsp)(nil),            // 11: rstream.io_rstream.protobuf.CloseTunnelRsp
	(*ProxyConnReq)(nil),              // 12: rstream.io_rstream.protobuf.ProxyConnReq
	(*ProxyConnRsp)(nil),              // 13: rstream.io_rstream.protobuf.ProxyConnRsp
	(*ProxyReq)(nil),                  // 14: rstream.io_rstream.protobuf.ProxyReq
	(*ProxyRsp)(nil),                  // 15: rstream.io_rstream.protobuf.ProxyRsp
	(*StreamReq)(nil),                 // 16: rstream.io_rstream.protobuf.StreamReq
	(*StreamRsp)(nil),                 // 17: rstream.io_rstream.protobuf.StreamRsp
	(*Heartbeat)(nil),                 // 18: rstream.io_rstream.protobuf.Heartbeat
	(*ServerMessage)(nil),             // 19: rstream.io_rstream.protobuf.ServerMessage
	(*Message)(nil),                   // 20: rstream.io_rstream.protobuf.Message
	nil,                               // 21: rstream.io_rstream.protobuf.TunnelProperties.LabelsEntry
	(*wrapperspb.StringValue)(nil),    // 22: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),      // 24: google.protobuf.BoolValue
	(*descriptorpb.FileOptions)(nil),  // 25: google.protobuf.FileOptions
	(*descriptorpb.FieldOptions)(nil), // 26: google.protobuf.FieldOptions
}
var file_pb_rstream_proto_depIdxs = []int32{
	22, // 0: rstream.io_rstream.protobuf.Error.message:type_name -> google.protobuf.StringValue
	22, // 1: rstream.io_rstream.protobuf.clientDetails.agent:type_name -> google.protobuf.StringValue
	22, // 2: rstream.io_rstream.protobuf.clientDetails.os:type_name -> google.protobuf.StringValue
	22, // 3: rstream.io_rstream.protobuf.clientDetails.arch:type_name -> google.protobuf.StringValue
	22, // 4: rstream.io_rstream.protobuf.clientDetails.version:type_name -> google.protobuf.StringValue
	22, // 5: rstream.io_rstream.protobuf.clientDetails.token:type_name -> google.protobuf.StringValue
	22, // 6: rstream.io_rstream.protobuf.clientDetails.protocol_version:type_name -> google.protobuf.StringValue
	22, // 7: rstream.io_rstream.protobuf.TunnelProperties.id:type_name -> google.protobuf.StringValue
	23, // 8: rstream.io_rstream.protobuf.TunnelProperties.creation_date:type_name -> google.protobuf.Timestamp
	22, // 9: rstream.io_rstream.protobuf.TunnelProperties.name:type_name -> google.protobuf.StringValue
	24, // 10: rstream.io_rstream.protobuf.TunnelProperties.publish:type_name -> google.protobuf.BoolValue
	22, // 11: rstream.io_rstream.protobuf.TunnelProperties.protocol:type_name -> google.protobuf.StringValue
	21, // 12: rstream.io_rstream.protobuf.TunnelProperties.labels:type_name -> rstream.io_rstream.protobuf.TunnelProperties.LabelsEntry
	22, // 13: rstream.io_rstream.protobuf.TunnelProperties.domain:type_name -> google.protobuf.StringValue
	22, // 14: rstream.io_rstream.protobuf.TunnelProperties.tls_mode:type_name -> google.protobuf.StringValue
	22, // 15: rstream.io_rstream.protobuf.TunnelProperties.tls_min_version:type_name -> google.protobuf.StringValue
	24, // 16: rstream.io_rstream.protobuf.TunnelProperties.mtls:type_name -> google.protobuf.BoolValue
	22, // 17: rstream.io_rstream.protobuf.TunnelProperties.mtls_cacert_pem:type_name -> google.protobuf.StringValue
	22, // 18: rstream.io_rstream.protobuf.TunnelProperties.http_version:type_name -> google.protobuf.StringValue
	24, // 19: rstream.io_rstream.protobuf.TunnelProperties.http_use_tls:type_name -> google.protobuf.BoolValue
	24, // 20: rstream.io_rstream.protobuf.TunnelProperties.token_auth:type_name -> google.protobuf.BoolValue
	24, // 21: rstream.io_rstream.protobuf.TunnelProperties.sso:type_name -> google.protobuf.BoolValue
	24, // 22: rstream.io_rstream.protobuf.TunnelProperties.challenge:type_name -> google.protobuf.BoolValue
	2,  // 23: rstream.io_rstream.protobuf.OpenControlChannelReq.client_details:type_name -> rstream.io_rstream.protobuf.clientDetails
	1,  // 24: rstream.io_rstream.protobuf.OpenControlChannelRsp.error:type_name -> rstream.io_rstream.protobuf.Error
	3,  // 25: rstream.io_rstream.protobuf.OpenTunnelReq.tunnel_properties:type_name -> rstream.io_rstream.protobuf.TunnelProperties
	3,  // 26: rstream.io_rstream.protobuf.OpenTunnelRsp.tunnel_properties:type_name -> rstream.io_rstream.protobuf.TunnelProperties
	1,  // 27: rstream.io_rstream.protobuf.OpenTunnelRsp.error:type_name -> rstream.io_rstream.protobuf.Error
	22, // 28: rstream.io_rstream.protobuf.ProxyConnReq.secret:type_name -> google.protobuf.StringValue
	0,  // 29: rstream.io_rstream.protobuf.ProxyConnReq.source_ip:type_name -> rstream.io_rstream.protobuf.IpAddress
	1,  // 30: rstream.io_rstream.protobuf.ProxyConnRsp.error:type_name -> rstream.io_rstream.protobuf.Error
	2,  // 31: rstream.io_rstream.protobuf.ProxyReq.client_details:type_name -> rstream.io_rstream.protobuf.clientDetails
	24, // 32: rstream.io_rstream.protobuf.ProxyReq.zero_rtt:type_name -> google.protobuf.BoolValue
	1,  // 33: rstream.io_rstream.protobuf.ProxyRsp.error:type_name -> rstream.io_rstream.protobuf.Error
	2,  // 34: rstream.io_rstream.protobuf.StreamReq.client_details:type_name -> rstream.io_rstream.protobuf.clientDetails
	24, // 35: rstream.io_rstream.protobuf.StreamReq.zero_rtt:type_name -> google.protobuf.BoolValue
	1,  // 36: rstream.io_rstream.protobuf.StreamRsp.error:type_name -> rstream.io_rstream.protobuf.Error
	4,  // 37: rstream.io_rstream.protobuf.Message.open_control_channel_req:type_name -> rstream.io_rstream.protobuf.OpenControlChannelReq
	5,  // 38: rstream.io_rstream.protobuf.Message.open_control_channel_rsp:type_name -> rstream.io_rstream.protobuf.OpenControlChannelRsp
	6,  // 39: rstream.io_rstream.protobuf.Message.close_control_channel_req:type_name -> rstream.io_rstream.protobuf.CloseControlChannelReq
	7,  // 40: rstream.io_rstream.protobuf.Message.close_control_channel_rsp:type_name -> rstream.io_rstream.protobuf.CloseControlChannelRsp
	8,  // 41: rstream.io_rstream.protobuf.Message.open_tunnel_req:type_name -> rstream.io_rstream.protobuf.OpenTunnelReq
	9,  // 42: rstream.io_rstream.protobuf.Message.open_tunnel_rsp:type_name -> rstream.io_rstream.protobuf.OpenTunnelRsp
	10, // 43: rstream.io_rstream.protobuf.Message.close_tunnel_req:type_name -> rstream.io_rstream.protobuf.CloseTunnelReq
	11, // 44: rstream.io_rstream.protobuf.Message.close_tunnel_rsp:type_name -> rstream.io_rstream.protobuf.CloseTunnelRsp
	12, // 45: rstream.io_rstream.protobuf.Message.proxy_conn_req:type_name -> rstream.io_rstream.protobuf.ProxyConnReq
	13, // 46: rstream.io_rstream.protobuf.Message.proxy_conn_rsp:type_name -> rstream.io_rstream.protobuf.ProxyConnRsp
	14, // 47: rstream.io_rstream.protobuf.Message.proxy_req:type_name -> rstream.io_rstream.protobuf.ProxyReq
	15, // 48: rstream.io_rstream.protobuf.Message.proxy_rsp:type_name -> rstream.io_rstream.protobuf.ProxyRsp
	16, // 49: rstream.io_rstream.protobuf.Message.stream_req:type_name -> rstream.io_rstream.protobuf.StreamReq
	17, // 50: rstream.io_rstream.protobuf.Message.stream_rsp:type_name -> rstream.io_rstream.protobuf.StreamRsp
	18, // 51: rstream.io_rstream.protobuf.Message.heartbeat:type_name -> rstream.io_rstream.protobuf.Heartbeat
	19, // 52: rstream.io_rstream.protobuf.Message.server_message:type_name -> rstream.io_rstream.protobuf.ServerMessage
	25, // 53: rstream.io_rstream.protobuf.protocol_version:extendee -> google.protobuf.FileOptions
	26, // 54: rstream.io_rstream.protobuf.access:extendee -> google.protobuf.FieldOptions
	55, // [55:55] is the sub-list for method output_type
	55, // [55:55] is the sub-list for method input_type
	55, // [55:55] is the sub-list for extension type_name
	53, // [53:55] is the sub-list for extension extendee
	0,  // [0:53] is the sub-list for field type_name
}

func init() { file_pb_rstream_proto_init() }
func file_pb_rstream_proto_init() {
	if File_pb_rstream_proto != nil {
		return
	}
	file_pb_rstream_proto_msgTypes[0].OneofWrappers = []any{
		(*IpAddress_V4)(nil),
		(*IpAddress_V6)(nil),
	}
	file_pb_rstream_proto_msgTypes[5].OneofWrappers = []any{
		(*OpenControlChannelRsp_ClientId)(nil),
		(*OpenControlChannelRsp_Error)(nil),
	}
	file_pb_rstream_proto_msgTypes[9].OneofWrappers = []any{
		(*OpenTunnelRsp_TunnelProperties)(nil),
		(*OpenTunnelRsp_Error)(nil),
	}
	file_pb_rstream_proto_msgTypes[17].OneofWrappers = []any{
		(*StreamRsp_StreamId)(nil),
		(*StreamRsp_Error)(nil),
	}
	file_pb_rstream_proto_msgTypes[20].OneofWrappers = []any{
		(*Message_OpenControlChannelReq)(nil),
		(*Message_OpenControlChannelRsp)(nil),
		(*Message_CloseControlChannelReq)(nil),
		(*Message_CloseControlChannelRsp)(nil),
		(*Message_OpenTunnelReq)(nil),
		(*Message_OpenTunnelRsp)(nil),
		(*Message_CloseTunnelReq)(nil),
		(*Message_CloseTunnelRsp)(nil),
		(*Message_ProxyConnReq)(nil),
		(*Message_ProxyConnRsp)(nil),
		(*Message_ProxyReq)(nil),
		(*Message_ProxyRsp)(nil),
		(*Message_StreamReq)(nil),
		(*Message_StreamRsp)(nil),
		(*Message_Heartbeat)(nil),
		(*Message_ServerMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rstream_proto_rawDesc), len(file_pb_rstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_pb_rstream_proto_goTypes,
		DependencyIndexes: file_pb_rstream_proto_depIdxs,
		MessageInfos:      file_pb_rstream_proto_msgTypes,
		ExtensionInfos:    file_pb_rstream_proto_extTypes,
	}.Build()
	File_pb_rstream_proto = out.File
	file_pb_rstream_proto_goTypes = nil
	file_pb_rstream_proto_depIdxs = nil
}
